const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const generatedHeader = `// AUTO-GENERATED FILE.\n// Do not edit this file directly.\n// Edit shared/curriculumCanonical.json and run npm run sync:curriculum.\n\n`;

const webManifest = `${generatedHeader}import {\n  lessonCatalog,\n  CURRICULUM_ENTRIES as RAW_CURRICULUM_ENTRIES,\n  getCurriculumEntriesForLevel as getRawCurriculumEntriesForLevel,\n  normalizeLevel,\n} from "./lessonCatalog.js";\nimport { alignB2CurriculumEntries } from "./b2LessonContentAlignment";\n\nconst CANONICAL_CURRICULUM = lessonCatalog;\nconst CURRICULUM_ENTRIES = alignB2CurriculumEntries(RAW_CURRICULUM_ENTRIES);\nconst CURRICULUM_BY_LEVEL = CURRICULUM_ENTRIES.reduce((acc, entry) => {\n  if (!acc[entry.level]) acc[entry.level] = [];\n  acc[entry.level].push(entry);\n  return acc;\n}, {});\nconst getCurriculumEntriesForLevel = (level) =>\n  alignB2CurriculumEntries(getRawCurriculumEntriesForLevel(level));\n\nexport {\n  CANONICAL_CURRICULUM,\n  CURRICULUM_ENTRIES,\n  CURRICULUM_BY_LEVEL,\n  getCurriculumEntriesForLevel,\n  normalizeLevel,\n};\n`;

const functionsManifest = `${generatedHeader}const {\n  lessonCatalog,\n  CURRICULUM_ENTRIES: RAW_CURRICULUM_ENTRIES,\n  getCurriculumEntriesForLevel: getRawCurriculumEntriesForLevel,\n  normalizeLevel,\n} = require('./lessonCatalog');\nconst { alignB2CurriculumEntries } = require('./b2LessonContentAlignment');\n\nconst CANONICAL_CURRICULUM = lessonCatalog;\nconst CURRICULUM_ENTRIES = alignB2CurriculumEntries(RAW_CURRICULUM_ENTRIES);\nconst CURRICULUM_BY_LEVEL = CURRICULUM_ENTRIES.reduce((acc, entry) => {\n  if (!acc[entry.level]) acc[entry.level] = [];\n  acc[entry.level].push(entry);\n  return acc;\n}, {});\nconst getCurriculumEntriesForLevel = (level) =>\n  alignB2CurriculumEntries(getRawCurriculumEntriesForLevel(level));\n\nmodule.exports = {\n  CANONICAL_CURRICULUM,\n  CURRICULUM_ENTRIES,\n  CURRICULUM_BY_LEVEL,\n  getCurriculumEntriesForLevel,\n  normalizeLevel,\n};\n`;

fs.writeFileSync(path.join(repoRoot, 'web/src/data/curriculumManifest.js'), webManifest, 'utf8');
fs.writeFileSync(path.join(repoRoot, 'functions/data/curriculumManifest.js'), functionsManifest, 'utf8');
console.log('Applied B2 Days 8–12 content alignment to generated curriculum manifests.');
