const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');
const { isDeepStrictEqual } = require('util');

const LEVELS_TO_AUDIT = new Set(['A1', 'A2', 'B1']);
const GENERATED_HEADER = '// AUTO-GENERATED FILE.\n// Do not edit this file directly.\n// Edit shared/curriculumCanonical.json and run npm run sync:curriculum.\n';
const B2_FUNCTIONS_ALIGNMENT_HEADER = '// AUTO-GENERATED FILE.\n// Do not edit this file directly.\n// Edit web/src/data/b2LessonContentAlignment.js and run npm run sync:curriculum.\n';
const GENERATED_FILES = [
  'web/src/data/lessonCatalog.js',
  'functions/data/lessonCatalog.js',
  'web/src/data/curriculumManifest.js',
  'functions/data/curriculumManifest.js',
  'web/src/data/a1CourseBookCards.js',
];
const ROUTE_PROPS = ['grammarPage', 'workbookRoute'];
const URL_PATTERN = /^(?:https?:|mailto:|tel:)/i;
const OPTIONAL_MEDIA_FIELDS = new Set([
  'video',
  'teacherVideo',
  'youtube_link',
  'aiVideo',
  'ai_video',
  'grammarExplainerVideo',
]);

const repoRoot = path.resolve(__dirname, '..');
const webAppPath = path.join(repoRoot, 'web/src/App.js');
const publicRoot = path.join(repoRoot, 'web/public');

const isLocalRoute = (value = '') => {
  const token = String(value || '').trim();
  return token.startsWith('/') && !URL_PATTERN.test(token);
};

const routeExists = (route, appSource) => {
  if (!isLocalRoute(route)) return true;
  const normalized = route.split(/[?#]/)[0].replace(/\/$/, '') || '/';
  const publicCandidates = [
    path.join(publicRoot, `${normalized}.html`),
    path.join(publicRoot, normalized, 'index.html'),
  ];
  const isDynamicLessonRoute = appSource.includes('path="/campus/course/lesson/:level/:day"')
    && /^\/campus\/course\/lesson\/(A1|A2|B1|B2|C1|C2)\/\d+$/i.test(normalized);

  return appSource.includes(`path="${normalized}"`)
    || isDynamicLessonRoute
    || publicCandidates.some((candidate) => fs.existsSync(candidate));
};

const canonicalResourceList = (entry) => {
  if (Array.isArray(entry.resources) && entry.resources.length) return entry.resources;
  return [{
    chapter: entry.chapter,
    title: entry.title,
    grammarPage: entry.grammarPage,
    workbookRoute: entry.workbookRoute,
    video: entry.video,
    submissionRequired: entry.submissionRequired,
    assignmentId: entry.assignmentId,
  }];
};

const structuralCurriculumValue = (value) => {
  if (Array.isArray(value)) return value.map(structuralCurriculumValue);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => !OPTIONAL_MEDIA_FIELDS.has(key))
      .map(([key, nested]) => [key, structuralCurriculumValue(nested)]),
  );
};

const structurallyEqual = (left, right) =>
  JSON.stringify(structuralCurriculumValue(left)) === JSON.stringify(structuralCurriculumValue(right));

const getB2AlignmentExpectedProjection = (alignment = {}) => ({
  ...alignment,
  topic: alignment.title,
  lessonTitle: alignment.title,
  assignmentTitle: alignment.title,
});

const getB2AlignmentProjectionFields = (alignment = {}) =>
  [...new Set([
    ...Object.keys(alignment),
    'topic',
    'lessonTitle',
    'assignmentTitle',
  ])];

const getB2AlignmentProjectionDrift = (entry = {}, alignment = {}) => {
  const expected = getB2AlignmentExpectedProjection(alignment);
  return getB2AlignmentProjectionFields(alignment).filter(
    (field) => !isDeepStrictEqual(entry?.[field], expected[field]),
  );
};

const validateCanonicalCurriculum = (canonical) => {
  const errors = [];
  const assignmentIds = new Map();
  const appSource = fs.existsSync(webAppPath) ? fs.readFileSync(webAppPath, 'utf8') : '';

  canonical.forEach((entry) => {
    const label = `${entry.level || '??'} day ${entry.day ?? '??'} ${entry.assignmentId || '(no assignmentId)'}`;
    const level = String(entry.level || '').toUpperCase();
    const assignmentId = String(entry.assignmentId || '').trim();
    const resources = canonicalResourceList(entry);

    if (entry.submissionRequired && !assignmentId) errors.push(`${label}: missing assignmentId`);
    if (assignmentId) {
      const previous = assignmentIds.get(assignmentId);
      if (previous) errors.push(`${label}: duplicate assignmentId also used by ${previous}`);
      assignmentIds.set(assignmentId, label);
    }

    const entrySubmission = Boolean(entry.submissionRequired);
    const submissionResources = resources.filter((resource) => Boolean(resource.submissionRequired ?? resource.assignment));
    if (entrySubmission && submissionResources.length === 0) {
      errors.push(`${label}: submissionRequired=true but no nested resource is marked for submission`);
    }
    if (!entrySubmission && submissionResources.length > 0) {
      errors.push(`${label}: submissionRequired=false but a nested resource requires submission`);
    }
    submissionResources.forEach((resource) => {
      const resourceId = String(resource.assignmentId || resource.assignment_id || '').trim();
      if (!resourceId) errors.push(`${label}: submission resource ${resource.chapter || '(no chapter)'} is missing assignmentId`);
      if (resourceId && resourceId !== assignmentId && resources.length === 1) {
        errors.push(`${label}: single submission resource uses ${resourceId}, conflicting with parent ${assignmentId}`);
      }
    });
    const contentStatus = entry.contentStatus === 'planned' ? 'planned' : 'published';
    const routeRequired = contentStatus !== 'planned';
    if (routeRequired && entry.kind === 'schreiben_sprechen' && !String(entry.workbookRoute || '').trim()) errors.push(`${label}: published workbook lesson missing workbookRoute`);
    if (routeRequired && entry.kind === 'grammar' && !String(entry.grammarPage || '').trim()) errors.push(`${label}: published grammar lesson missing grammarPage`);
    if (routeRequired && entry.submissionRequired && !String(entry.workbookRoute || entry.grammarPage || '').trim()) errors.push(`${label}: published required lesson missing workbookRoute or grammarPage`);

    if (LEVELS_TO_AUDIT.has(level)) {
      if (!String(entry.title || '').trim()) errors.push(`${label}: missing title`);
      resources.forEach((resource, resourceIndex) => {
        const resourceLabel = `${label} resource ${resourceIndex + 1}${resource.chapter ? ` (${resource.chapter})` : ''}`;
        if (!String(resource.title || entry.title || '').trim()) errors.push(`${resourceLabel}: missing title`);
        ROUTE_PROPS.forEach((prop) => {
          const route = String(resource[prop] || '').trim();
          if (route && !routeExists(route, appSource)) errors.push(`${resourceLabel}: local ${prop} route not found: ${route}`);
        });
      });
    }
  });

  return errors;
};

(async () => {
  const canonical = JSON.parse(fs.readFileSync(path.join(repoRoot, 'shared/curriculumCanonical.json'), 'utf8'));
  // Runtime manifests intentionally import browser-only alignment helpers. Compare
  // the generated canonical catalogues directly and treat media URLs as optional;
  // IDs, routes, assignments, ordering and progression metadata remain strict.
  const webCatalogModule = await import(pathToFileURL(path.join(repoRoot, 'web/src/data/lessonCatalog.js')));
  const webB2AlignmentModule = await import(pathToFileURL(path.join(repoRoot, 'web/src/data/b2LessonContentAlignment.js')));
  const functionsModule = require(path.join(repoRoot, 'functions/data/curriculumManifest.js'));
  const functionsB2AlignmentModule = require(path.join(repoRoot, 'functions/data/b2LessonContentAlignment.js'));

  const webCanonical = webCatalogModule.lessonCatalog || [];
  const functionsCanonical = functionsModule.CANONICAL_CURRICULUM || [];
  const webB2Alignment = webB2AlignmentModule.B2_LESSON_CONTENT_ALIGNMENT || {};
  const functionsB2Alignment = functionsB2AlignmentModule.B2_LESSON_CONTENT_ALIGNMENT || {};
  const errors = [];

  if (!structurallyEqual(canonical, webCanonical) || !structurallyEqual(canonical, functionsCanonical)) {
    errors.push('Structural curriculum manifest drift detected. Run: npm run sync:curriculum');
  }

  if (JSON.stringify(webB2Alignment) !== JSON.stringify(functionsB2Alignment)) {
    errors.push('B2 lesson content alignment drift detected between web and Functions. Run: npm run sync:curriculum');
  }

  const functionsB2Entries = functionsModule.getCurriculumEntriesForLevel('B2') || [];
  Object.values(webB2Alignment).forEach((alignment) => {
    const rawWebEntry = webCanonical.find((entry) =>
      String(entry.level || '').toUpperCase() === 'B2'
      && Number(entry.day) === Number(alignment.day)
    );
    const serverEntry = functionsB2Entries.find((entry) => Number(entry.day) === Number(alignment.day));

    if (!rawWebEntry) {
      errors.push(`Web B2 canonical curriculum is missing aligned Day ${alignment.day}.`);
      return;
    }
    if (!serverEntry) {
      errors.push(`Functions B2 curriculum is missing aligned Day ${alignment.day}.`);
      return;
    }

    const webRuntimeEntry = webB2AlignmentModule.alignB2CurriculumEntry(rawWebEntry);
    const functionsRuntimeEntry = functionsB2AlignmentModule.alignB2CurriculumEntry(rawWebEntry);
    const webDrift = getB2AlignmentProjectionDrift(webRuntimeEntry, alignment);
    const functionsHelperDrift = getB2AlignmentProjectionDrift(functionsRuntimeEntry, alignment);
    const functionsManifestDrift = getB2AlignmentProjectionDrift(serverEntry, alignment);

    if (webDrift.length) {
      errors.push(`Web B2 Day ${alignment.day} aligned runtime projection drifted in: ${webDrift.join(', ')}.`);
    }
    if (functionsHelperDrift.length) {
      errors.push(`Functions B2 Day ${alignment.day} alignment helper drifted in: ${functionsHelperDrift.join(', ')}.`);
    }
    if (functionsManifestDrift.length) {
      errors.push(`Functions B2 Day ${alignment.day} runtime manifest drifted in: ${functionsManifestDrift.join(', ')}.`);
    }

    const projectionFields = getB2AlignmentProjectionFields(alignment);
    const webFunctionsRuntimeMismatch = projectionFields.filter(
      (field) => !isDeepStrictEqual(webRuntimeEntry?.[field], functionsRuntimeEntry?.[field])
        || !isDeepStrictEqual(webRuntimeEntry?.[field], serverEntry?.[field]),
    );
    if (webFunctionsRuntimeMismatch.length) {
      errors.push(`B2 Day ${alignment.day} web/Functions runtime mismatch in: ${webFunctionsRuntimeMismatch.join(', ')}.`);
    }
  });

  const functionsB2AlignmentSource = fs.readFileSync(path.join(repoRoot, 'functions/data/b2LessonContentAlignment.js'), 'utf8');
  if (!functionsB2AlignmentSource.startsWith(B2_FUNCTIONS_ALIGNMENT_HEADER)) {
    errors.push('functions/data/b2LessonContentAlignment.js: missing generated-file warning header');
  }

  GENERATED_FILES.forEach((relativePath) => {
    const source = fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');
    if (!source.startsWith(GENERATED_HEADER)) errors.push(`${relativePath}: missing generated-file warning header`);
  });

  errors.push(...validateCanonicalCurriculum(canonical));

  if (errors.length) {
    console.error(`Curriculum validation failed with ${errors.length} issue(s):`);
    errors.forEach((error) => console.error(`- ${error}`));
    process.exit(1);
  }

  console.log('Curriculum structure and complete B2 aligned runtime projection are synced across web and Functions.');
})();
