import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const file = path.join(root, "web/src/data/c2LessonContentAlignment.js");
let source = fs.readFileSync(file, "utf8");

const marker = "const C2_TOPIC_DRIVEN_REDESIGN = Object.freeze({";

const redesign = `const C2_TOPIC_DRIVEN_REDESIGN = Object.freeze({
  1: { title: "Kreislaufwirtschaft und Wegwerfgesellschaft", topic: "Wie können Konsum, Reparatur und Wiederverwendung nachhaltiger organisiert werden?", writingPrompt: "Verfassen Sie eine differenzierte Stellungnahme zur Frage, wie Politik, Unternehmen und Verbraucher die Wegwerfgesellschaft begrenzen können.", planningPrompt: "Planen Sie These, Begründung, Gegenposition und Synthese und achten Sie auf einen adressatengerechten Registerwechsel.", collocations: [["Ressourcen im Kreislauf halten","keep resources in circulation","Eine funktionierende Kreislaufwirtschaft hält wertvolle Ressourcen möglichst lange im Kreislauf."],["Produkte länger nutzen","use products for longer","Reparierbare Geräte ermöglichen es, Produkte deutlich länger zu nutzen."],["Abfall vermeiden","avoid waste","Mehrwegsysteme können helfen, unnötigen Abfall zu vermeiden."],["Reparaturen fördern","promote repairs","Steuerliche Anreize könnten Reparaturen stärker fördern."],["Rohstoffe zurückgewinnen","recover raw materials","Aus Altgeräten lassen sich wichtige Rohstoffe zurückgewinnen."],["eine Wegwerfmentalität überwinden","overcome a throwaway mentality","Bildung und transparente Preise können dazu beitragen, eine Wegwerfmentalität zu überwinden."]] },
  2: { title: "Schulpflicht und Bildungsgerechtigkeit", topic: "Welche Aufgaben haben Schule und Staat bei der Sicherung fairer Bildungschancen?", writingPrompt: "Erörtern Sie, wie Schulpflicht, Förderung und soziale Herkunft Bildungschancen beeinflussen.", planningPrompt: "Ordnen Sie bekannte und neue Informationen klar und nutzen Sie Thema–Rhema und das Vorfeld gezielt." },
  3: { title: "Wissenschaft, Forschung und Hochschulen", topic: "Wie entstehen belastbare Erkenntnisse und welche Verantwortung tragen Hochschulen?", writingPrompt: "Nehmen Sie Stellung zum Verhältnis von Forschungsfreiheit, gesellschaftlichem Nutzen und öffentlicher Finanzierung.", planningPrompt: "Planen Sie eine sachliche Argumentation und wechseln Sie bewusst zwischen Nominal- und Verbalstil." },
  4: { title: "Journalismus, Nachrichten und Quellenkritik", topic: "Wie lassen sich glaubwürdige Quellen von unbelegten Behauptungen unterscheiden?", writingPrompt: "Verfassen Sie einen analytischen Text über die Verantwortung von Medien im Umgang mit unsicheren oder widersprüchlichen Informationen.", planningPrompt: "Kennzeichnen Sie fremde Aussagen sauber und nutzen Sie indirekte Rede zur Distanzierung." },
  5: { title: "Politik, Verantwortung und öffentliches Vertrauen", topic: "Wie sollten politische Aussagen, Versprechen und Verantwortungszuschreibungen bewertet werden?", writingPrompt: "Erörtern Sie, wodurch öffentliches Vertrauen in politische Institutionen gestärkt oder geschwächt wird.", planningPrompt: "Unterscheiden Sie Hörensagen, Selbstaussage und Wahrscheinlichkeitsgrade mit subjektiver Modalität." },
  6: { title: "Soziale Ungleichheit und Chancengerechtigkeit", topic: "Welche Ursachen und Folgen haben soziale und wirtschaftliche Ungleichheiten?", writingPrompt: "Diskutieren Sie Maßnahmen zur Verringerung struktureller Ungleichheit und deren mögliche Nebenwirkungen.", planningPrompt: "Trennen Sie Korrelation und Kausalität und wählen Sie kausale Ausdrücke nach Evidenzstärke." },
  7: { title: "Arbeitswelt, Leistungsdruck und Work-Life-Balance", topic: "Wie verändern Leistungsanforderungen, Flexibilität und neue Arbeitsformen den Alltag?", writingPrompt: "Nehmen Sie Stellung dazu, wie Unternehmen Produktivität und gesunde Arbeitsbedingungen miteinander vereinbaren können.", planningPrompt: "Nutzen Sie Funktionsverbgefüge nur dort, wo sie Präzision oder idiomatische Verdichtung verbessern." },
  8: { title: "Künstliche Intelligenz und Automatisierung", topic: "Welche Chancen, Risiken und Verantwortlichkeiten entstehen durch automatisierte Systeme?", writingPrompt: "Erörtern Sie, unter welchen Bedingungen KI in Bildung, Arbeit oder Verwaltung eingesetzt werden sollte.", planningPrompt: "Verdichten Sie Informationen mit Partizipialattributen, ohne die Lesbarkeit zu verlieren." },
  9: { title: "Datenschutz und digitale Selbstbestimmung", topic: "Wie viel Kontrolle sollten Menschen über ihre Daten und digitale Profile behalten?", writingPrompt: "Verfassen Sie eine Stellungnahme zu personalisierter Datennutzung und digitaler Selbstbestimmung.", planningPrompt: "Variieren Sie Passiv- und Ersatzformen und unterscheiden Sie Möglichkeit, Pflicht und unpersönliche Darstellung." },
  10: { title: "Medizin, Gesundheit und Forschungsethik", topic: "Wie sollten medizinische Innovation, Nutzen, Risiko und Verantwortung gegeneinander abgewogen werden?", writingPrompt: "Erörtern Sie eine medizinethische Entscheidung, bei der Nutzen, Risiko und unsichere Evidenz gegeneinander abgewogen werden müssen.", planningPrompt: "Markieren Sie Wahrscheinlichkeitsgrade präzise und vermeiden Sie unbelegte Gewissheit." },
  11: { title: "Klimaschutz, Nachhaltigkeit und Mobilität", topic: "Wie lassen sich ökologische Ziele, soziale Interessen und Mobilitätsbedürfnisse verbinden?", writingPrompt: "Nehmen Sie Stellung zu einer klimapolitischen Maßnahme und integrieren Sie mindestens einen starken Einwand.", planningPrompt: "Nutzen Sie konzessive und adversative Strukturen, um Gegenpositionen präzise einzubauen." },
  12: { title: "Migration, Integration und gesellschaftliche Teilhabe", topic: "Welche Bedingungen fördern Integration, Anerkennung und gleichberechtigte Teilhabe?", writingPrompt: "Erörtern Sie, welche institutionellen und gesellschaftlichen Maßnahmen Teilhabe erleichtern können.", planningPrompt: "Achten Sie auf sichere Verb-, Nomen- und Adjektivrektion sowie Kasuspräzision." },
  13: { title: "Sprache, Mehrsprachigkeit und kulturelle Identität", topic: "Wie prägen Sprache, Mehrsprachigkeit und Erinnerung individuelle und kollektive Identität?", writingPrompt: "Verfassen Sie einen differenzierten Text über Mehrsprachigkeit und kulturelle Zugehörigkeit.", planningPrompt: "Analysieren und bilden Sie komplexe Wörter bewusst; prüfen Sie jede Neubildung auf Stil und Verständlichkeit." },
  14: { title: "Kultur, Literatur und gesellschaftliches Gedächtnis", topic: "Wie beeinflussen Texte, Kunst und Erinnerung die Deutung gesellschaftlicher Erfahrungen?", writingPrompt: "Analysieren Sie, wie sprachliche Bilder und Konnotationen eine kulturelle oder gesellschaftliche Deutung steuern.", planningPrompt: "Trennen Sie Denotation, Konnotation und Metaphorik und belegen Sie Ihre Interpretation am sprachlichen Material." },
  15: { title: "Wohnen, Mieten und Lebensqualität", topic: "Wie verändern Wohnkosten, Stadtentwicklung und Lage die Lebensqualität?", writingPrompt: "Erörtern Sie politische und gesellschaftliche Möglichkeiten, bezahlbaren Wohnraum zu sichern.", planningPrompt: "Vergleichen und gewichten Sie Positionen präzise mit fortgeschrittenen Vergleichs- und Intensivierungsstrukturen.", collocations: [["bezahlbaren Wohnraum schaffen","create affordable housing","Städte müssen langfristig mehr bezahlbaren Wohnraum schaffen."],["Mieten begrenzen","limit rents","Umstritten ist, ob strengere Regeln steigende Mieten wirksam begrenzen."],["Wohnraum zur Verfügung stellen","provide housing","Kommunale Gesellschaften können zusätzlichen Wohnraum zur Verfügung stellen."],["unter hohen Wohnkosten leiden","suffer from high housing costs","Vor allem Haushalte mit geringem Einkommen leiden unter hohen Wohnkosten."],["Lebensqualität erhöhen","increase quality of life","Grünflächen und kurze Wege können die Lebensqualität deutlich erhöhen."],["in Ballungsräumen wohnen","live in metropolitan areas","Wer in Ballungsräumen wohnt, muss häufig höhere Mietkosten tragen."]] },
  16: { title: "Konsum, Werbung und Kaufverhalten", topic: "Wie beeinflussen Werbung, Personalisierung und soziale Erwartungen Kaufentscheidungen?", writingPrompt: "Nehmen Sie Stellung zur Wirkung personalisierter Werbung auf Konsumverhalten und Entscheidungsfreiheit.", planningPrompt: "Verdichten und hierarchisieren Sie Informationen mit Relativsatz, Partizipialattribut, Nominalisierung und Apposition." },
  17: { title: "Kindergarten, Kinderbetreuung und Familienpolitik", topic: "Welche Voraussetzungen braucht gute frühkindliche Bildung und verlässliche Betreuung?", writingPrompt: "Erörtern Sie, welche Bedingungen für einen gerechten Zugang zu hochwertiger Kinderbetreuung erfüllt sein müssen.", planningPrompt: "Formulieren Sie Bedingungen und Voraussetzungen differenziert mit sofern, falls und vorausgesetzt, dass.", collocations: [["Betreuungsplätze ausbauen","expand childcare places","Kommunen müssen Betreuungsplätze ausbauen, damit Familien verlässlich planen können."],["frühkindliche Bildung fördern","promote early childhood education","Gut ausgestattete Einrichtungen können frühkindliche Bildung gezielt fördern."],["Familien entlasten","relieve families","Flexible Öffnungszeiten können berufstätige Familien erheblich entlasten."],["pädagogische Qualität sichern","ensure educational quality","Mehr Plätze allein reichen nicht aus, wenn die pädagogische Qualität nicht gesichert ist."],["Zugang zu Betreuung gewährleisten","ensure access to childcare","Der Staat sollte einen verlässlichen Zugang zu Betreuung gewährleisten."],["an Voraussetzungen geknüpft sein","be tied to conditions","Zusätzliche Förderung kann an klare Qualitätsstandards geknüpft sein."]] },
  18: { title: "Studium, Weiterbildung und lebenslanges Lernen", topic: "Wie verändern Weiterbildung und Hochschulbildung berufliche und gesellschaftliche Chancen?", writingPrompt: "Erörtern Sie rückblickend, welche Folgen frühere Bildungsentscheidungen haben können und welche Alternativen denkbar gewesen wären.", planningPrompt: "Nutzen Sie Konjunktiv II der Vergangenheit für irreale Bedingungen, alternative Entwicklungen und Folgen.", collocations: [["eine Weiterbildung absolvieren","complete further training","Viele Beschäftigte absolvieren eine Weiterbildung, um mit technologischem Wandel Schritt zu halten."],["Kenntnisse vertiefen","deepen knowledge","Ein berufsbegleitendes Studium kann vorhandene Kenntnisse gezielt vertiefen."],["Bildungschancen verbessern","improve educational opportunities","Stipendien können Bildungschancen für einkommensschwächere Gruppen verbessern."],["eine Qualifikation nachholen","obtain a qualification later","Digitale Angebote erleichtern es Erwachsenen, eine Qualifikation nachzuholen."],["berufliche Perspektiven eröffnen","open career prospects","Weiterbildung kann neue berufliche Perspektiven eröffnen."],["eine Gelegenheit ungenutzt lassen","leave an opportunity unused","Ohne Beratung hätte sie eine wichtige Weiterbildungsmöglichkeit möglicherweise ungenutzt gelassen."]] },
  19: { title: "Globalisierung, Handel und wirtschaftliche Abhängigkeiten", topic: "Wie verändern globale Verflechtungen Wirtschaft, Macht und politische Handlungsspielräume?", writingPrompt: "Nehmen Sie Stellung dazu, wie Staaten wirtschaftliche Offenheit und strategische Unabhängigkeit ausbalancieren sollten.", planningPrompt: "Nutzen Sie komplexe Konnektoren semantisch präzise und vermeiden Sie austauschbare Verknüpfungen." },
  20: { title: "Soziale Medien, Debattenkultur und Meinungsbildung", topic: "Wie beeinflussen digitale Plattformen Sprache, Haltung und öffentliche Debatten?", writingPrompt: "Analysieren Sie, wie soziale Medien Debattenkultur und öffentliche Meinungsbildung verändern.", planningPrompt: "Nutzen Sie Diskurspartikeln kontrolliert, um Haltung und Gesprächsnuancen zu markieren.", collocations: [["eine Debatte anstoßen","spark a debate","Ein viraler Beitrag kann innerhalb weniger Stunden eine breite Debatte anstoßen."],["öffentliche Meinung prägen","shape public opinion","Plattformen können die öffentliche Meinung indirekt prägen."],["Beiträge einordnen","contextualise posts","Nutzer sollten zugespitzte Beiträge kritisch einordnen."],["eine Haltung erkennen lassen","reveal a stance","Schon kleine Partikeln können eine bestimmte Haltung erkennen lassen."],["Reichweite erzielen","achieve reach","Emotional formulierte Inhalte erzielen häufig besonders große Reichweite."],["den Ton einer Diskussion verschärfen","intensify the tone of a discussion","Polarisierende Formulierungen können den Ton einer Diskussion schnell verschärfen."]] },
  21: { title: "Verwaltung, Bürgerservice und gesellschaftliche Institutionen", topic: "Wie sollten Institutionen Entscheidungen, Leistungen und Verantwortung sprachlich transparent machen?", writingPrompt: "Verfassen Sie einen sachlich-formellen Text über eine institutionelle Entscheidung und ihre Auswirkungen auf Bürgerinnen und Bürger.", planningPrompt: "Nutzen Sie feste Verb-Nomen-Verbindungen idiomatisch und vermeiden Sie wörtliche Übersetzungen.", collocations: [["eine Entscheidung treffen","make a decision","Die Behörde trifft ihre Entscheidung auf Grundlage der geltenden Regelung."],["einen Antrag stellen","submit an application","Betroffene können einen Antrag auf Unterstützung stellen."],["Auskunft erteilen","provide information","Die zuständige Stelle muss verbindliche Auskunft erteilen."],["eine Maßnahme ergreifen","take a measure","Bei wiederholten Problemen sollte die Verwaltung geeignete Maßnahmen ergreifen."],["zur Verfügung stehen","be available","Digitale Beratungsangebote stehen inzwischen rund um die Uhr zur Verfügung."],["Verantwortung übernehmen","assume responsibility","Öffentliche Institutionen müssen für nachvollziehbare Verfahren Verantwortung übernehmen."]] },
  22: { title: "Reisen, Tourismus und kulturelle Begegnung", topic: "Wie verändern Reisen, Tourismus und Mobilität Orte, Menschen und kulturelle Wahrnehmung?", writingPrompt: "Erörtern Sie Chancen und Belastungen des internationalen Tourismus für lokale Gesellschaften.", planningPrompt: "Stellen Sie Abläufe und zeitliche Beziehungen mit präzisen temporalen Strukturen dar.", collocations: [["eine Reise unternehmen","take a trip","Viele Menschen unternehmen Reisen, um neue Kulturen kennenzulernen."],["lokale Strukturen belasten","strain local structures","Massentourismus kann Verkehr, Wohnraum und lokale Strukturen erheblich belasten."],["kulturelle Begegnungen ermöglichen","enable cultural encounters","Austauschprogramme ermöglichen intensive kulturelle Begegnungen."],["Tourismus nachhaltig gestalten","make tourism sustainable","Regionen versuchen zunehmend, Tourismus nachhaltiger zu gestalten."],["eine Region erschließen","develop/open up a region","Neue Verkehrsverbindungen können abgelegene Regionen touristisch erschließen."],["Reiseverhalten verändern","change travel behaviour","Steigende Kosten und Klimaschutzdebatten verändern das Reiseverhalten vieler Menschen."]] },
  23: { title: "Internationale Zusammenarbeit und Diplomatie", topic: "Wie lassen sich Konflikte, Interessen und Kooperation diplomatisch verhandeln?", writingPrompt: "Formulieren Sie eine diplomatische Stellungnahme, die Zustimmung, Vorbehalt und einen Kompromissvorschlag verbindet.", planningPrompt: "Nutzen Sie Hedging und vorsichtige Kritik, ohne Ihre eigentliche Position unklar zu machen." },
  24: { title: "Gesellschaftliche Kontroversen und öffentliche Debatten", topic: "Wie lässt sich eine kontroverse Position logisch, fair und evidenzbasiert vertreten?", writingPrompt: "Verfassen Sie eine vollständige C2-Stellungnahme zu einer gesellschaftlich kontroversen Frage.", planningPrompt: "Bauen Sie These, Begründung, Beleg, Einwand, Reaktion und Schluss als erkennbare Argumentationslinie auf." },
  25: { title: "Daten, Statistik und wissenschaftliche Evidenz", topic: "Wie stark dürfen Schlussfolgerungen aus Daten, Studien und Korrelationen formuliert werden?", writingPrompt: "Bewerten Sie eine hypothetische Studie und erklären Sie, welche Aussagen durch die Daten gestützt werden und welche nicht.", planningPrompt: "Stufen Sie Aussagen nach Evidenzgrad ab und vermeiden Sie unbelegte Kausalität." },
  26: { title: "Philosophie, Ethik und technischer Fortschritt", topic: "Wie lassen sich abstrakte Begriffe und ethische Konflikte logisch und sprachlich präzise untersuchen?", writingPrompt: "Erörtern Sie eine ethische Frage des technischen Fortschritts mit klaren Prämissen und einer nachvollziehbaren Schlussfolgerung.", planningPrompt: "Nutzen Sie komplexe Satzperioden nur dort, wo die logische Hierarchie klar bleibt." },
  27: { title: "Akademisches Schreiben und formelle Korrespondenz", topic: "Wie wird ein anspruchsvoller Text präzise, kohärent, adressatengerecht und stilistisch sicher überarbeitet?", writingPrompt: "Überarbeiten Sie einen formellen oder akademischen Text auf Präzision, Register, Kohäsion und Redundanz.", planningPrompt: "Prüfen Sie Wortwahl, Bezüge, Satzbau und Register systematisch und ersetzen Sie schwache Formulierungen." },
  28: { title: "C2 Prüfungssimulation: Stellungnahme, Umformung und Synthese", topic: "Wie werden Register, Evidenz, Reformulierung und Argumentation unter Prüfungsbedingungen kombiniert?", writingPrompt: "Bearbeiten Sie eine vollständige C2-Simulationsaufgabe mit Stellungnahme, Reformulierung und abschließender Synthese.", planningPrompt: "Wählen Sie Strukturen nach Funktion, sichern Sie Kohäsion und prüfen Sie Register, Nuance und Evidenz in der Endkontrolle." },
});`;

if (!source.includes(marker)) {
  const anchor = "// Extra collocations are deliberately keyed by the canonical C2 day.";
  if (!source.includes(anchor)) throw new Error("C2 topic redesign anchor missing: canonical mastery block");
  source = source.replace(anchor, `${redesign}\n\n${anchor}`);
}

const masteryAnchor = `  const canonical = getCanonicalC2Mastery(dayNumber);\n  const mastery = canonical || source;\n  if (!mastery) return null;\n\n  const collocations = uniqueCollocations([\n    ...(Array.isArray(mastery.collocations) ? mastery.collocations : []),\n    ...(C2_COLLOCATION_SUPPLEMENTS[dayNumber] || []),\n  ]).slice(0, 6);`;
const masteryReplacement = `  const canonical = getCanonicalC2Mastery(dayNumber);\n  const mastery = canonical || source;\n  if (!mastery) return null;\n  const topicRedesign = C2_TOPIC_DRIVEN_REDESIGN[dayNumber] || {};\n\n  const collocations = Array.isArray(topicRedesign.collocations)\n    ? topicRedesign.collocations\n    : uniqueCollocations([\n        ...(Array.isArray(mastery.collocations) ? mastery.collocations : []),\n        ...(C2_COLLOCATION_SUPPLEMENTS[dayNumber] || []),\n      ]).slice(0, 6);`;
if (!source.includes("const topicRedesign = C2_TOPIC_DRIVEN_REDESIGN[dayNumber] || {};")) {
  if (!source.includes(masteryAnchor)) throw new Error("C2 topic redesign anchor missing: enhanceC2Mastery");
  source = source.replace(masteryAnchor, masteryReplacement);
}

const returnAnchor = `  return {\n    ...source,\n    ...mastery,\n    collocationTopic: mastery.title,`;
const returnReplacement = `  return {\n    ...source,\n    ...mastery,\n    ...topicRedesign,\n    collocationTopic: topicRedesign.title || mastery.title,`;
if (!source.includes("    ...topicRedesign,")) {
  if (!source.includes(returnAnchor)) throw new Error("C2 topic redesign anchor missing: aligned return");
  source = source.replace(returnAnchor, returnReplacement);
}

const writingAnchor = `      prompt: mastery.challenge || mastery.production,\n      planningPrompt: mastery.production || "Plan the content before writing.",`;
const writingReplacement = `      prompt: topicRedesign.writingPrompt || mastery.challenge || mastery.production,\n      planningPrompt: topicRedesign.planningPrompt || mastery.production || "Plan the content before writing.",`;
if (!source.includes("topicRedesign.writingPrompt")) {
  if (!source.includes(writingAnchor)) throw new Error("C2 topic redesign anchor missing: writing exercise");
  source = source.replace(writingAnchor, writingReplacement);
}

fs.writeFileSync(file, source, "utf8");
console.log("Restored topic-driven C2 Days 1-28 with concrete Goethe-style domains; Day 1 is Kreislaufwirtschaft und Wegwerfgesellschaft.");
