const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const canonicalPath = path.join(repoRoot, 'shared/curriculumCanonical.json');
const a1CardsPath = path.join(repoRoot, 'shared/a1CourseBookCards.json');
const webManifestPath = path.join(repoRoot, 'web/src/data/curriculumManifest.js');
const functionsManifestPath = path.join(repoRoot, 'functions/data/curriculumManifest.js');
const webA1CardsPath = path.join(repoRoot, 'web/src/data/a1CourseBookCards.js');

const entries = JSON.parse(fs.readFileSync(canonicalPath, 'utf8'));
const a1Document = JSON.parse(fs.readFileSync(a1CardsPath, 'utf8'));
const a1Cards = Array.isArray(a1Document.cards) ? a1Document.cards : [];

const header = `// Generated from shared/curriculumCanonical.json by scripts/syncCurriculumManifest.js.\n// Do not edit this file directly; edit the canonical JSON and rerun npm run sync:curriculum.\n\n`;
const common = `const LEVEL_PATTERN = /^(A1|A2|B1|B2|C1|C2)$/;

const normalizeLevel = (value = "") => {
  const token = String(value || "").trim().toUpperCase();
  return LEVEL_PATTERN.test(token) ? token : "";
};

const toArray = (value) => Array.isArray(value) ? value : value ? [value] : [];

const firstString = (...values) => values.find((value) => typeof value === "string" && value.trim())?.trim() || "";

const normalizeLessonResource = (resource = {}, entry = {}) => {
  const submissionRequired = Boolean(resource.submissionRequired ?? resource.assignment ?? false);
  const assignmentId = submissionRequired ? String(resource.assignmentId || resource.assignment_id || entry.assignmentId || "").trim() : "";
  const normalized = {
    ...resource,
    chapter: String(resource.chapter || entry.chapter || "").trim(),
    title: String(resource.title || entry.title || "").trim(),
    video: firstString(resource.video, resource.youtube_link),
    youtube_link: firstString(resource.youtube_link, resource.video) || null,
    grammarPage: firstString(resource.grammarPage, resource.grammarbook_link, resource.grammar_link),
    grammarbook_link: firstString(resource.grammarbook_link, resource.grammarPage, resource.grammar_link) || null,
    grammar_link: firstString(resource.grammar_link, resource.grammarPage, resource.grammarbook_link) || null,
    workbookRoute: firstString(resource.workbookRoute, resource.workbook_link),
    workbook_link: firstString(resource.workbook_link, resource.workbookRoute) || null,
    assignment: submissionRequired,
    submissionRequired,
  };

  if (assignmentId) {
    normalized.assignmentId = assignmentId;
    normalized.assignment_id = assignmentId;
  } else {
    delete normalized.assignmentId;
    delete normalized.assignment_id;
  }

  return normalized;
};

const normalizeCanonicalEntry = (entry) => {
  const level = normalizeLevel(entry.level);
  const chapter = String(entry.chapter || "").trim();
  const assignmentId = String(entry.assignmentId || (level && chapter ? level + "-" + chapter : "")).trim();
  const title = String(entry.title || "").trim();
  const assignmentType = String(entry.assignmentType || "").trim();
  const submissionRequired = Boolean(entry.submissionRequired);
  const progressionEligible = Boolean(entry.progressionEligible);
  const resources = toArray(entry.resources).length
    ? toArray(entry.resources).map((item) => normalizeLessonResource(item, { ...entry, assignmentId }))
    : [normalizeLessonResource({
        chapter,
        title,
        video: entry.video || "",
        grammarPage: entry.grammarPage || "",
        workbookRoute: entry.workbookRoute || "",
        submissionRequired,
        assignmentId,
      }, { ...entry, assignmentId })];
  const submissionResource = resources.find((item) => item.submissionRequired) || resources[0] || {};
  const practiceResources = resources.filter((item) => !item.submissionRequired);

  return {
    ...entry,
    level,
    assignmentDay: Number(entry.day),
    day: Number(entry.day),
    chapter,
    title,
    topic: title,
    mode: assignmentType,
    type: assignmentType,
    assignmentType,
    assignment: submissionRequired,
    submissionRequired,
    progressionEligible,
    canonicalAssignmentId: assignmentId,
    assignmentId,
    assignment_id: assignmentId,
    grammarPage: entry.grammarPage || "",
    workbookRoute: entry.workbookRoute || "",
    video: entry.video || "",
    resources,
    lesen_hören: resources.filter((item) => item.kind !== "schreiben_sprechen" && item.submissionRequired),
    schreiben_sprechen: practiceResources.length ? practiceResources : { grammar_link: entry.grammarPage || null, workbook_link: entry.workbookRoute || null, assignment: false },
    primaryResource: submissionResource,
  };
};

const CANONICAL_CURRICULUM = ${JSON.stringify(entries, null, 2)};

const CURRICULUM_ENTRIES = CANONICAL_CURRICULUM.map(normalizeCanonicalEntry);

const CURRICULUM_BY_LEVEL = CURRICULUM_ENTRIES.reduce((acc, entry) => {
  if (!acc[entry.level]) acc[entry.level] = [];
  acc[entry.level].push(entry);
  return acc;
}, {});

const getCurriculumEntriesForLevel = (level) => {
  const normalizedLevel = normalizeLevel(level);
  return normalizedLevel ? [...(CURRICULUM_BY_LEVEL[normalizedLevel] || [])] : [];
};
`;

const a1Module = `// Generated from shared/a1CourseBookCards.json by scripts/syncCurriculumManifest.js.\n// Do not edit this file directly.\n\nconst A1_COURSE_BOOK_CARDS = Object.freeze(${JSON.stringify(a1Cards)}.map((card)=>Object.freeze(card)));
const normalizeA1Token=(value="")=>String(value||"").trim().toLowerCase().replace(/\\s+/g," ");
const getA1CourseBookCard=({displayDay,chapter,assignmentId,title}={})=>{
  const day=Number(displayDay);
  const normalizedChapter=String(chapter||"").trim();
  const normalizedAssignmentId=String(assignmentId||"").trim().toUpperCase();
  const normalizedTitle=normalizeA1Token(title);
  const exact=A1_COURSE_BOOK_CARDS.find((card)=>Number(card.displayDay)===day&&card.chapter===normalizedChapter);
  if(exact)return exact;
  const legacy=A1_COURSE_BOOK_CARDS.find((card)=>Number(card.displayDay)===day&&(card.legacyMatches||[]).some((match)=>String(match.chapter||"").trim()===normalizedChapter&&(!match.title||normalizeA1Token(match.title)===normalizedTitle)));
  if(legacy)return legacy;
  return A1_COURSE_BOOK_CARDS.find((card)=>normalizedAssignmentId&&String(card.assignmentId||"").trim().toUpperCase()===normalizedAssignmentId&&(!Number.isFinite(day)||Number(card.displayDay)===day))||null;
};
export {A1_COURSE_BOOK_CARDS,getA1CourseBookCard};
`;

fs.writeFileSync(webManifestPath, `${header}${common}\nexport { CANONICAL_CURRICULUM, CURRICULUM_ENTRIES, CURRICULUM_BY_LEVEL, getCurriculumEntriesForLevel, normalizeLevel };\n`, 'utf8');
fs.writeFileSync(functionsManifestPath, `${header}${common}\nmodule.exports = { CANONICAL_CURRICULUM, CURRICULUM_ENTRIES, CURRICULUM_BY_LEVEL, getCurriculumEntriesForLevel, normalizeLevel };\n`, 'utf8');
fs.writeFileSync(webA1CardsPath, a1Module, 'utf8');
console.log('Generated curriculum manifests and the A1 course-book card module from shared sources.');
