export const styles = {
  container: {
    maxWidth: 900,
    margin: "0 auto",
    padding: "24px 16px 40px",
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
    backgroundColor: "#f3f4f6",
    minHeight: "100vh",
  },
  header: {
    marginBottom: 24,
    textAlign: "center",
  },
  title: {
    fontSize: 28,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#4b5563",
    marginBottom: 12,
  },
  nav: {
    display: "flex",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  navButton: {
    padding: "10px 16px",
    borderRadius: 999,
    border: "1px solid #d1d5db",
    backgroundColor: "#ffffff",
    cursor: "pointer",
    fontWeight: 600,
  },
  navButtonActive: {
    padding: "10px 16px",
    borderRadius: 999,
    border: "1px solid #2563eb",
    backgroundColor: "#2563eb",
    color: "#ffffff",
    cursor: "pointer",
    fontWeight: 600,
  },
  card: {
    background: "#ffffff",
    borderRadius: 12,
    padding: 16,
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.05)",
    marginBottom: 16,
    border: "1px solid #e5e7eb",
  },
  resultCard: {
    background: "#ffffff",
    borderRadius: 12,
    padding: 16,
    boxShadow: "0 8px 16px rgba(0, 0, 0, 0.08)",
    marginTop: 16,
    border: "1px solid #d1d5db",
  },
  sectionTitle: {
    margin: "0 0 12px 0",
    fontSize: 18,
  },
  resultHeading: {
    fontSize: 16,
    marginTop: 12,
    marginBottom: 4,
  },
  resultText: {
    fontSize: 14,
    color: "#111827",
  },
  score: {
    fontSize: 16,
  },
  row: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    marginTop: 8,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 180,
    gap: 4,
  },
  label: {
    fontSize: 13,
    color: "#374151",
  },
  select: {
    padding: "6px 8px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    fontSize: 14,
  },
  primaryButton: {
    padding: "8px 16px",
    borderRadius: 999,
    border: "none",
    cursor: "pointer",
    fontWeight: 600,
    background: "#2563eb",
    color: "#ffffff",
    fontSize: 14,
  },
  secondaryButton: {
    padding: "8px 16px",
    borderRadius: 999,
    border: "1px solid #d1d5db",
    cursor: "pointer",
    background: "#f9fafb",
    fontSize: 14,
  },
  dangerButton: {
    padding: "8px 16px",
    borderRadius: 999,
    border: "none",
    cursor: "pointer",
    fontWeight: 600,
    background: "#dc2626",
    color: "#ffffff",
    fontSize: 14,
  },
  helperText: {
    fontSize: 13,
    color: "#4b5563",
    marginBottom: 8,
  },
  textArea: {
    width: "100%",
    padding: 12,
    borderRadius: 12,
    border: "1px solid #d1d5db",
    fontSize: 14,
    resize: "vertical",
    minHeight: 120,
    boxSizing: "border-box",
  },
  pre: {
    background: "#111827",
    color: "#e5e7eb",
    padding: 12,
    borderRadius: 8,
    whiteSpace: "pre-wrap",
    fontSize: 13,
    margin: 0,
  },
  vocabGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 12,
    marginTop: 12,
  },
  vocabCard: {
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: 12,
    background: "#f9fafb",
  },
  vocabTitle: {
    margin: "0 0 8px 0",
    fontSize: 15,
  },
  vocabList: {
    paddingLeft: 18,
    margin: 0,
    display: "grid",
    gap: 4,
  },
  promptList: {
    paddingLeft: 18,
    margin: 0,
    display: "grid",
    gap: 6,
  },
  errorBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 10,
    background: "#fef3c7",
    color: "#92400e",
    border: "1px solid #f59e0b",
    fontSize: 13,
  },
};

export const vocabPrompts = [
  "Beschreibe dich selbst mit 5–6 Sätzen (Name, Herkunft, Beruf, Hobbys).",
  "Stelle drei Fragen zu einem Thema deiner Wahl (z. B. Urlaub, Arbeit, Familie).",
  "Mache höfliche Bitten für ein Gruppenprojekt (Treffpunkt, Aufgaben, Zeitplan).",
];
