export const styles = {
  container: {
    maxWidth: 1180,
    margin: "0 auto",
    padding: "24px 16px 40px",
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
    backgroundColor: "#f3f4f6",
    minHeight: "100vh",
  },
  header: {
    marginBottom: 24,
    textAlign: "center",
  },
  title: {
    fontSize: 28,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#4b5563",
    marginBottom: 12,
  },
  nav: {
    display: "flex",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  focusNotice: {
    marginBottom: 12,
    padding: 10,
    borderRadius: 12,
    border: "1px dashed #6366f1",
    background: "#eef2ff",
    color: "#312e81",
    fontSize: 13,
    textAlign: "center",
  },
  navButton: {
    padding: "10px 16px",
    borderRadius: 999,
    border: "1px solid #d1d5db",
    backgroundColor: "#ffffff",
    cursor: "pointer",
    fontWeight: 600,
  },
  navButtonActive: {
    padding: "10px 16px",
    borderRadius: 999,
    border: "1px solid #2563eb",
    backgroundColor: "#2563eb",
    color: "#ffffff",
    cursor: "pointer",
    fontWeight: 600,
  },
  card: {
    background: "#ffffff",
    borderRadius: 12,
    padding: 16,
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.05)",
    marginBottom: 16,
    border: "1px solid #e5e7eb",
  },
  resultCard: {
    background: "#ffffff",
    borderRadius: 12,
    padding: 16,
    boxShadow: "0 8px 16px rgba(0, 0, 0, 0.08)",
    marginTop: 16,
    border: "1px solid #d1d5db",
  },
  sectionTitle: {
    margin: "0 0 12px 0",
    fontSize: 18,
  },
  resultHeading: {
    fontSize: 16,
    marginTop: 12,
    marginBottom: 4,
  },
  resultText: {
    fontSize: 14,
    color: "#111827",
  },
  score: {
    fontSize: 16,
  },
  row: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    marginTop: 8,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 180,
    gap: 4,
  },
  label: {
    fontSize: 13,
    color: "#374151",
  },
  select: {
    padding: "6px 8px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    fontSize: 14,
  },
  primaryButton: {
    padding: "8px 16px",
    borderRadius: 999,
    border: "none",
    cursor: "pointer",
    fontWeight: 600,
    background: "#2563eb",
    color: "#ffffff",
    fontSize: 14,
  },
  secondaryButton: {
    padding: "8px 16px",
    borderRadius: 999,
    border: "1px solid #d1d5db",
    cursor: "pointer",
    background: "#f9fafb",
    fontSize: 14,
  },
  dangerButton: {
    padding: "8px 16px",
    borderRadius: 999,
    border: "none",
    cursor: "pointer",
    fontWeight: 600,
    background: "#dc2626",
    color: "#ffffff",
    fontSize: 14,
  },
  helperText: {
    fontSize: 13,
    color: "#4b5563",
    marginBottom: 8,
  },
  textArea: {
    width: "100%",
    padding: 12,
    borderRadius: 12,
    border: "1px solid #d1d5db",
    fontSize: 14,
    resize: "vertical",
    minHeight: 120,
    boxSizing: "border-box",
  },
  pre: {
    background: "#111827",
    color: "#e5e7eb",
    padding: 12,
    borderRadius: 8,
    whiteSpace: "pre-wrap",
    fontSize: 13,
    margin: 0,
  },
  vocabGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 12,
    marginTop: 12,
  },
  vocabCard: {
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: 12,
    background: "#f9fafb",
  },
  vocabTitle: {
    margin: "0 0 8px 0",
    fontSize: 15,
  },
  vocabList: {
    paddingLeft: 18,
    margin: 0,
    display: "grid",
    gap: 4,
  },
  promptList: {
    paddingLeft: 18,
    margin: 0,
    display: "grid",
    gap: 6,
  },
  errorBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 10,
    background: "#fef3c7",
    color: "#92400e",
    border: "1px solid #f59e0b",
    fontSize: 13,
  },
  successBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 10,
    background: "#ecfdf3",
    color: "#166534",
    border: "1px solid #22c55e",
    fontSize: 13,
  },
  lockPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 10px",
    borderRadius: 999,
    background: "#fef2f2",
    color: "#991b1b",
    fontWeight: 700,
    border: "1px solid #fecaca",
  },
  segmentedControl: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 8,
    background: "#f9fafb",
    padding: 6,
    borderRadius: 12,
    border: "1px solid #e5e7eb",
    marginBottom: 12,
  },
  segmentedButton: {
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid transparent",
    background: "transparent",
    fontWeight: 600,
    color: "#374151",
    cursor: "pointer",
  },
  segmentedActive: {
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid #2563eb",
    background: "#2563eb",
    color: "#ffffff",
    fontWeight: 700,
    boxShadow: "0 6px 18px rgba(37, 99, 235, 0.25)",
    cursor: "pointer",
  },
  recordCard: {
    background: "linear-gradient(180deg, #ecfeff, #f8fafc)",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 12,
    display: "grid",
    gap: 12,
    justifyItems: "center",
  },
  recordStatus: {
    fontSize: 14,
    fontWeight: 700,
    color: "#0f172a",
  },
  recordButton: {
    width: 120,
    height: 120,
    borderRadius: "50%",
    border: "10px solid #bfdbfe",
    background: "#2563eb",
    color: "#ffffff",
    fontWeight: 800,
    fontSize: 18,
    boxShadow: "0 10px 30px rgba(37, 99, 235, 0.35)",
    cursor: "pointer",
  },
  recordButtonActive: {
    width: 120,
    height: 120,
    borderRadius: "50%",
    border: "10px solid #fecdd3",
    background: "#dc2626",
    color: "#ffffff",
    fontWeight: 800,
    fontSize: 18,
    boxShadow: "0 10px 30px rgba(220, 38, 38, 0.35)",
    cursor: "pointer",
  },
  recordMetaRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  },
  recordTimer: {
    fontSize: 14,
    fontWeight: 700,
    color: "#0f172a",
  },
  waveform: {
    display: "flex",
    alignItems: "flex-end",
    gap: 4,
    height: 52,
    flexGrow: 1,
  },
  uploadCard: {
    background: "#f8fafc",
    border: "1px dashed #cbd5e1",
    borderRadius: 12,
    padding: 12,
  },
  uploadLabel: {
    display: "inline-block",
    padding: "10px 14px",
    borderRadius: 10,
    border: "1px solid #2563eb",
    background: "#2563eb",
    color: "#ffffff",
    fontWeight: 700,
    cursor: "pointer",
  },
  tabList: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 8,
    margin: "12px 0 16px",
  },
  tabButton: {
    padding: "12px 14px",
    borderRadius: 12,
    border: "1px solid #e5e7eb",
    background: "#f9fafb",
    cursor: "pointer",
    fontWeight: 700,
    color: "#111827",
  },
  tabButtonActive: {
    padding: "12px 14px",
    borderRadius: 12,
    border: "1px solid #2563eb",
    background: "#2563eb",
    cursor: "pointer",
    fontWeight: 800,
    color: "#ffffff",
    boxShadow: "0 10px 24px rgba(37, 99, 235, 0.25)",
  },
  levelPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 10px",
    background: "#eef2ff",
    color: "#3730a3",
    borderRadius: 999,
    fontWeight: 700,
    fontSize: 12,
    border: "1px solid #c7d2fe",
  },
  metaRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    margin: "8px 0 10px",
  },
  timer: {
    fontSize: 28,
    fontWeight: 800,
    color: "#0f172a",
    letterSpacing: 1,
  },
  timerHelp: {
    fontSize: 13,
    color: "#4b5563",
    marginTop: 6,
  },
  badge: {
    display: "inline-block",
    padding: "6px 10px",
    background: "#f3f4f6",
    borderRadius: 10,
    border: "1px solid #e5e7eb",
    fontSize: 12,
    fontWeight: 700,
    color: "#1f2937",
  },
  checklist: {
    display: "grid",
    gap: 8,
    paddingLeft: 18,
    margin: "8px 0 0",
  },
  chatHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  promptChips: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  promptChip: {
    padding: "8px 12px",
    borderRadius: 999,
    border: "1px solid #d1d5db",
    background: "#f8fafc",
    cursor: "pointer",
    fontWeight: 600,
  },
  chatShell: {
    display: "grid",
    gap: 12,
    gridTemplateRows: "1fr auto",
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    overflow: "hidden",
    background: "#f9fafb",
  },
  chatLogWide: {
    display: "grid",
    gap: 10,
    maxHeight: 420,
    overflowY: "auto",
    padding: 12,
    background: "#f8fafc",
  },
  chatLog: {
    display: "grid",
    gap: 10,
    maxHeight: 320,
    overflowY: "auto",
    padding: 4,
  },
  chatBubbleCoach: {
    background: "#eef2ff",
    border: "1px solid #c7d2fe",
    borderRadius: 14,
    padding: 12,
    color: "#1f2937",
    fontSize: 14,
  },
  chatBubbleUser: {
    background: "#ecfeff",
    border: "1px solid #a5f3fc",
    borderRadius: 14,
    padding: 12,
    color: "#0f172a",
    fontSize: 14,
  },
  chatTimestamp: {
    fontSize: 11,
    color: "#6b7280",
  },
  chatComposer: {
    background: "#ffffff",
    padding: 12,
    borderTop: "1px solid #e5e7eb",
    display: "grid",
    gap: 8,
  },
  recorderRow: {
    display: "grid",
    gap: 8,
    alignItems: "center",
    gridTemplateColumns: "auto 1fr",
  },
  recorderButton: {
    padding: "10px 14px",
    borderRadius: 999,
    border: "1px solid #d1d5db",
    background: "#ecfeff",
    cursor: "pointer",
    fontWeight: 700,
  },
  recorderButtonActive: {
    padding: "10px 14px",
    borderRadius: 999,
    border: "1px solid #ef4444",
    background: "#fef2f2",
    cursor: "pointer",
    fontWeight: 700,
    color: "#b91c1c",
  },
  composerRow: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: "1fr auto",
    alignItems: "center",
  },
  chatTextarea: {
    width: "100%",
    padding: 12,
    borderRadius: 12,
    border: "1px solid #d1d5db",
    fontSize: 14,
    resize: "vertical",
    minHeight: 80,
    boxSizing: "border-box",
  },
  sendButton: {
    padding: "12px 18px",
    borderRadius: 12,
    border: "none",
    cursor: "pointer",
    fontWeight: 700,
    background: "#2563eb",
    color: "#ffffff",
    minWidth: 100,
  },
  textareaSmall: {
    width: "100%",
    padding: 10,
    borderRadius: 10,
    border: "1px solid #d1d5db",
    fontSize: 14,
    resize: "vertical",
    minHeight: 80,
    boxSizing: "border-box",
  },
  gridTwo: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
  },
};

export const vocabPrompts = [
  "Beschreibe dich selbst mit 5–6 Sätzen (Name, Herkunft, Beruf, Hobbys).",
  "Stelle drei Fragen zu einem Thema deiner Wahl (z. B. Urlaub, Arbeit, Familie).",
  "Mache höfliche Bitten für ein Gruppenprojekt (Treffpunkt, Aufgaben, Zeitplan).",
];
