import React, { useMemo, useState } from "react";
import { styles } from "../styles";

const byDay = {
  1:{topic:"Alltag und erste Gespräche",items:[["sprechen mit + Dat","to speak with","Ich spreche mit meiner Lehrerin."],["sprechen über + Akk","to talk about","Wir sprechen über den Kurs."],["fragen nach + Dat","to ask about","Ich frage nach dem Termin."]]},
  2:{topic:"Tagesablauf und Termine",items:[["warten auf + Akk","to wait for","Ich warte auf den Bus."],["beginnen mit + Dat","to begin with","Wir beginnen mit der Übung."],["denken an + Akk","to think of/about","Ich denke an meinen Termin."]]},
  3:{topic:"Menschen und Dinge vergleichen",items:[["sich interessieren für + Akk","to be interested in","Ich interessiere mich für Technik."],["sprechen über + Akk","to talk about","Wir sprechen über unsere Hobbys."],["passen zu + Dat","to suit/go with","Die Jacke passt zu der Hose."]]},
  4:{topic:"Treffen und Verabredungen",items:[["sich treffen mit + Dat","to meet with","Ich treffe mich mit Anna."],["warten auf + Akk","to wait for","Wir warten auf dich."],["sich freuen auf + Akk","to look forward to","Ich freue mich auf unser Treffen."]]},
  5:{topic:"Freizeit",items:[["sich interessieren für + Akk","to be interested in","Ich interessiere mich für Musik."],["teilnehmen an + Dat","to take part in","Ich nehme an einem Kurs teil."],["sich treffen mit + Dat","to meet with","Am Samstag treffe ich mich mit Freunden."]]},
  6:{topic:"Wohnung, Möbel und Räume",items:[["wohnen bei + Dat","to live with/at","Ich wohne bei meinen Eltern."],["passen zu + Dat","to match","Der Tisch passt zum Sofa."],["sich kümmern um + Akk","to take care of","Ich kümmere mich um die Wohnung."]]},
  7:{topic:"Wohnung beschreiben",items:[["suchen nach + Dat","to search for","Wir suchen nach einer Wohnung."],["sich interessieren für + Akk","to be interested in","Ich interessiere mich für die Wohnung."],["gehören zu + Dat","to belong to","Der Balkon gehört zur Wohnung."]]},
  8:{topic:"Bitten und Anweisungen",items:[["bitten um + Akk","to ask for","Ich bitte um Hilfe."],["achten auf + Akk","to pay attention to","Achte auf die Tür."],["helfen bei + Dat","to help with","Kannst du mir bei der Aufgabe helfen?"]]},
  9:{topic:"Vergangenheit und Erlebnisse",items:[["erzählen von + Dat","to tell about","Er erzählt von seiner Reise."],["denken an + Akk","to think about","Ich denke oft an den Urlaub."],["sich erinnern an + Akk","to remember","Ich erinnere mich an den ersten Tag."]]},
  10:{topic:"Vergangenheit erzählen",items:[["sprechen über + Akk","to talk about","Wir sprechen über unsere Kindheit."],["träumen von + Dat","to dream of","Als Kind träumte ich von einem Hund."],["sich erinnern an + Akk","to remember","Sie erinnert sich an ihre Schulzeit."]]},
  11:{topic:"Vergleichen und bewerten",items:[["sich entscheiden für + Akk","to decide for","Ich entscheide mich für das billigere Modell."],["abhängen von + Dat","to depend on","Die Wahl hängt vom Preis ab."],["passen zu + Dat","to suit","Dieses Angebot passt zu meinem Budget."]]},
  12:{topic:"Traumberuf",items:[["sich interessieren für + Akk","to be interested in","Ich interessiere mich für Medizin."],["arbeiten als","to work as","Ich möchte als Ärztin arbeiten."],["sich vorbereiten auf + Akk","to prepare for","Ich bereite mich auf den Beruf vor."]]},
  13:{topic:"Vorstellungsgespräch",items:[["sich bewerben um + Akk","to apply for","Ich bewerbe mich um die Stelle."],["sich bewerben bei + Dat","to apply at","Ich bewerbe mich bei einer Firma."],["sprechen über + Akk","to talk about","Wir sprechen über meine Erfahrung."]]},
  14:{topic:"Beruf und Karriere",items:[["arbeiten an + Dat","to work on","Ich arbeite an meinen Sprachkenntnissen."],["sich vorbereiten auf + Akk","to prepare for","Ich bereite mich auf die Prüfung vor."],["sich entscheiden für + Akk","to decide on","Ich entscheide mich für eine Ausbildung."]]},
  15:{topic:"Sport",items:[["teilnehmen an + Dat","to participate in","Ich nehme an einem Turnier teil."],["sich interessieren für + Akk","to be interested in","Ich interessiere mich für Fußball."],["sich freuen über + Akk","to be happy about","Ich freue mich über den Sieg."]]},
  16:{topic:"Wohlbefinden",items:[["sich kümmern um + Akk","to take care of","Ich kümmere mich um meine Gesundheit."],["leiden unter + Dat","to suffer from","Er leidet unter Stress."],["sich erholen von + Dat","to recover from","Ich erhole mich von der Arbeit."]]},
  17:{topic:"Apotheke und Gesundheit",items:[["fragen nach + Dat","to ask for/about","Ich frage nach einem Medikament."],["helfen gegen + Akk","to help against","Was hilft gegen Kopfschmerzen?"],["sprechen mit + Dat","to speak with","Ich spreche mit der Apothekerin."]]},
  18:{topic:"Bank und Telefonieren",items:[["fragen nach + Dat","to ask about","Ich frage nach den Gebühren."],["bitten um + Akk","to ask for","Ich bitte um eine Auskunft."],["sprechen mit + Dat","to speak with","Ich spreche mit einem Mitarbeiter."]]},
  19:{topic:"Einkaufen",items:[["bezahlen für + Akk","to pay for","Ich bezahle für die Jacke."],["sich entscheiden für + Akk","to choose","Ich entscheide mich für das blaue Hemd."],["fragen nach + Dat","to ask for","Ich frage nach einer anderen Größe."]]},
  20:{topic:"Reklamation",items:[["sich beschweren über + Akk","to complain about","Ich beschwere mich über das Produkt."],["bitten um + Akk","to ask for","Ich bitte um eine Rückerstattung."],["warten auf + Akk","to wait for","Ich warte auf Ihre Antwort."]]},
  21:{topic:"Wochenende planen",items:[["sich verabreden mit + Dat","to arrange to meet","Ich verabrede mich mit Freunden."],["sich entscheiden für + Akk","to decide on","Wir entscheiden uns für einen Ausflug."],["sich freuen auf + Akk","to look forward to","Wir freuen uns auf das Wochenende."]]},
  22:{topic:"Die Woche planen",items:[["sich vorbereiten auf + Akk","to prepare for","Ich bereite mich auf den Montag vor."],["denken an + Akk","to remember/think of","Denk an deinen Termin."],["sich kümmern um + Akk","to take care of","Ich kümmere mich um die Einkäufe."]]},
  23:{topic:"Schule, Arbeit und Verkehr",items:[["fahren mit + Dat","to travel by","Ich fahre mit dem Bus."],["warten auf + Akk","to wait for","Ich warte auf die Bahn."],["sich entscheiden für + Akk","to choose","Ich entscheide mich für das Fahrrad."]]},
  24:{topic:"Urlaub planen",items:[["sich freuen auf + Akk","to look forward to","Ich freue mich auf den Urlaub."],["sich entscheiden für + Akk","to decide on","Wir entscheiden uns für Spanien."],["sich informieren über + Akk","to get information about","Ich informiere mich über das Hotel."]]},
  25:{topic:"Pläne und Möglichkeiten",items:[["denken an + Akk","to think about","Ich denke an meine nächsten Schritte."],["sich entscheiden für + Akk","to decide on","Ich entscheide mich für einen Kurs."],["sprechen über + Akk","to talk about","Wir sprechen über unsere Pläne."]]},
  26:{topic:"Bedingungen und Entscheidungen",items:[["abhängen von + Dat","to depend on","Die Reise hängt vom Wetter ab."],["sich vorbereiten auf + Akk","to prepare for","Ich bereite mich auf den Termin vor."],["sich entscheiden gegen + Akk","to decide against","Wir entscheiden uns gegen das Auto."]]},
  27:{topic:"Digitale Kommunikation",items:[["schreiben an + Akk","to write to","Ich schreibe an meine Lehrerin."],["antworten auf + Akk","to reply to","Ich antworte auf die Nachricht."],["sprechen über + Akk","to talk about","Wir sprechen über soziale Medien."]]},
  28:{topic:"Zukunft",items:[["sich vorbereiten auf + Akk","to prepare for","Ich bereite mich auf die Zukunft vor."],["hoffen auf + Akk","to hope for","Ich hoffe auf eine gute Zukunft."],["denken an + Akk","to think about","Ich denke an meine beruflichen Ziele."]]}
};

export const getA2TopicCollocations = (day) => byDay[Number(day)] || null;

export default function A2TopicCollocationPractice({ day }) {
  const lesson = useMemo(() => getA2TopicCollocations(day), [day]);
  const [answers, setAnswers] = useState({});
  if (!lesson) return null;
  const questions = lesson.items.map(([combo]) => ({ combo, prep: combo.includes(" + ") ? combo.split(" + ")[0].split(" ").slice(-1)[0] : "" }));
  return <section style={{ ...styles.card, display:"grid", gap:14, border:"1px solid #bae6fd", borderRadius:18, background:"#f8fdff" }}>
    <div><span style={{ ...styles.badge, background:"#e0f2fe", color:"#075985" }}>A2 · Wortschatz + Grammatik</span><h2 style={{ margin:"8px 0 4px" }}>Verben mit Präpositionen</h2><p style={{ margin:0, color:"#475569" }}>{lesson.topic}: Lerne die ganze Verbindung als Einheit.</p></div>
    <div style={{ display:"grid", gap:10 }}>{lesson.items.map(([combo,en,example]) => <div key={combo} style={{ border:"1px solid #e2e8f0", borderRadius:14, padding:12, background:"#fff" }}><strong>{combo}</strong><div style={{ color:"#64748b", marginTop:3 }}>{en}</div><div style={{ marginTop:6 }}>{example}</div></div>)}</div>
    <div style={{ display:"grid", gap:10 }}><strong>Kurz prüfen</strong>{questions.filter(({prep})=>prep).map(({combo,prep},index)=>{const options=[prep,"auf","mit","von"].filter((v,i,a)=>a.indexOf(v)===i).slice(0,4); const chosen=answers[index]; return <div key={combo} style={{ border:"1px solid #e2e8f0", borderRadius:14, padding:12, display:"grid", gap:8 }}><span>{index+1}. Welche Präposition gehört zu <strong>{combo.split(" + ")[0].replace(new RegExp(` ${prep}$`),"")}</strong>?</span><div style={{ display:"flex", gap:8, flexWrap:"wrap" }}>{options.map(option=><button key={option} type="button" style={styles.secondaryButton} onClick={()=>setAnswers(old=>({...old,[index]:option}))}>{option}</button>)}</div>{chosen?<strong style={{ color:chosen===prep?"#166534":"#991b1b" }}>{chosen===prep?"Richtig.":`Noch nicht. Richtig ist: ${prep}.`}</strong>:null}</div>})}</div>
    <div style={{ border:"1px solid #bbf7d0", background:"#f0fdf4", borderRadius:14, padding:12 }}><strong>Jetzt selbst bilden:</strong> Sage oder schreibe zwei Sätze zum heutigen Thema und benutze zwei Verbindungen aus der Liste.</div>
  </section>;
}
