import React from "react";
import B1StandardWorkbookPage from "./B1StandardWorkbookPage";

export const B1_DAY16_PRUEFUNGSANGST_STRESSBEWAELTIGUNG_WORKBOOK_CONFIG = {
  day: 16,
  chapter: "5.16",
  assignmentKey: "B1-5.16",
  workbookId: "B1Day16PruefungsangstStressbewaeltigung",
  title: "Prüfungsangst und Stressbewältigung",
  subtitle: "Sprich über Prüfungsangst, Symptome und Strategien gegen Stress. Teil 1 ist Gruppenpraxis; Teil 2, Teil 3 und Teil 4 bereitest du für die Abgabe vor.",
  heroImage: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=1600&q=80",
  heroAlt: "Schüler bereitet sich auf eine Prüfung vor",
  speaking: {
    question: "Wie gehst du mit Prüfungsangst und Stress um?",
    instructions: "Bereite eine kurze B1-Präsentation über Prüfungsangst und Stressbewältigung vor. Erkläre Ursachen, Symptome, Strategien und deine eigene Erfahrung.",
    image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Lernen vor einer Prüfung",
    ideaTitle: "Zentrales Thema: Prüfungsangst und Stressbewältigung",
    ideaIntro: "In this chapter, we'll engage in group exercises discussing exam anxiety, stress symptoms and practical strategies for staying calm.",
    ideaGroups: [
      {
        title: "1. Ursachen von Prüfungsangst",
        items: [
          "Zu wenig Vorbereitung: Angst, weil man nicht genug gelernt hat.",
          "Zeitdruck: das Gefühl, nicht genug Zeit zu haben.",
          "Hohe Erwartungen: Druck von Eltern, Lehrern oder sich selbst.",
          "Blackout: Angst, in der Prüfung nichts mehr zu wissen.",
          "Vergleich mit anderen: Andere sind besser vorbereitet oder haben bessere Noten.",
        ],
      },
      {
        title: "2. Symptome von Prüfungsangst",
        items: [
          "Körperliche Symptome: Herzrasen, Schwitzen, Zittern.",
          "Mentale Symptome: Konzentrationsprobleme, negative Gedanken.",
          "Emotionale Symptome: Angst, Nervosität, Unsicherheit.",
          "Verhalten: Schlafprobleme, Prokrastination, Gereiztheit.",
        ],
      },
      {
        title: "3. Strategien zur Stressbewältigung",
        items: [
          "Gute Vorbereitung: frühzeitig lernen und einen Zeitplan erstellen.",
          "Entspannungstechniken: Atemübungen, Meditation, Musik hören.",
          "Bewegung: Sport treiben oder spazieren gehen.",
          "Schlaf: genug schlafen, um fit zu sein.",
          "Gesunde Ernährung: keine Energy-Drinks, sondern gesunde Snacks.",
          "Positive Gedanken: Ich kann das schaffen! Ich bin gut vorbereitet!",
          "Unterstützung suchen: mit Familie oder Freunden reden.",
        ],
      },
      {
        title: "4. Tipps für die Prüfung",
        items: [
          "Pünktlich sein und früh genug ankommen.",
          "Ruhig atmen und tief durchatmen.",
          "Fragen genau lesen und nicht überstürzen.",
          "Schritt für Schritt lösen: zuerst einfache Aufgaben, dann schwierige.",
          "Zeit einteilen und nicht zu lange an einer Aufgabe hängen bleiben.",
        ],
      },
      {
        title: "5. Eigene Erfahrungen und Meinung",
        items: [
          "Hattest du schon einmal Prüfungsangst? Wie hast du dich gefühlt?",
          "Welche Strategien helfen dir am besten gegen Stress?",
          "Wie bereitest du dich auf Prüfungen vor?",
          "Denkst du, Prüfungsangst ist normal? Warum?",
        ],
      },
    ],
    exampleTitle: "Beispielantwort",
    exampleSteps: [
      "Vor Prüfungen bin ich oft nervös, aber ich versuche, mich gut vorzubereiten.",
      "Ich mache einen Lernplan und wiederhole die wichtigsten Themen.",
      "Vor der Prüfung höre ich ruhige Musik und atme tief durch.",
      "Das hilft mir, mich zu entspannen.",
    ],
    activityTitle: "Struktur deiner Präsentation",
    activityPoints: [
      "Begrüßung und Vorstellung des Themas: Ich möchte heute über Prüfungsangst und Stress sprechen.",
      "Inhalt und Struktur: Prüfungsangst bedeutet, dass man vor oder während einer Prüfung sehr nervös ist.",
      "Persönliche Erfahrung: Ich habe selbst Prüfungsstress erlebt oder kenne jemanden, der darunter leidet.",
      "Situation in deinem Heimatland: In meinem Heimatland empfinden viele Schüler und Studenten Prüfungen als stressig, weil ...",
      "Vor- und Nachteile: Ein Vorteil von Stress ist, dass er motivieren kann. Ein Nachteil ist, dass er die Leistung verschlechtern kann.",
      "Schluss und Dank: Zusammenfassend kann ich sagen, dass es wichtig ist, mit Prüfungsangst richtig umzugehen. Danke fürs Zuhören!",
    ],
    activityOrdered: true,
    answerStructure: [
      "Begrüße dein Publikum und nenne das Thema.",
      "Erkläre, was Prüfungsangst bedeutet.",
      "Beschreibe Ursachen und Symptome.",
      "Nenne Strategien gegen Stress.",
      "Erzähle kurz von deiner Erfahrung oder der Situation in deinem Heimatland.",
      "Bewerte Vor- und Nachteile von Stress und schließe mit einem Fazit.",
    ],
    usefulPhrases: [
      "Prüfungsangst bedeutet, dass ...",
      "Viele Schüler sind nervös, weil ...",
      "Ein häufiges Symptom ist ...",
      "Mir hilft es, wenn ich ...",
      "Man sollte frühzeitig lernen und Pausen machen.",
      "Zusammenfassend ist wichtig, dass ...",
    ],
  },
  writing: {
    title: "Kann man Prüfungsangst mit der richtigen Stressbewältigung reduzieren?",
    instructions: "Lesen Sie Julias Meinung und schreiben Sie Ihre eigene Antwort. Sagen Sie, ob Sie zustimmen oder nicht, und begründen Sie Ihre Meinung mit Beispielen.",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Prüfungsvorbereitung und Stressbewältigung",
    sourceTitle: "Aufgabe",
    sourceText: "Kann man Prüfungsangst mit der richtigen Stressbewältigung reduzieren? Schreiben Sie Ihre Meinung. Julia: Viele Menschen haben Angst vor Prüfungen, weil sie unter Druck stehen. Ich stimme dem zu, denn Nervosität kann die Leistung beeinflussen. Dennoch gibt es viele Strategien, um besser mit Stress umzugehen, wie gute Vorbereitung oder Entspannungsübungen. Ich finde, dass jeder seine eigene Methode finden sollte, um ruhig zu bleiben und sich sicher zu fühlen. Was denken Sie darüber?",
    taskPoints: [
      "Beziehen Sie sich kurz auf Julias Meinung.",
      "Schreiben Sie, ob Sie zustimmen oder nicht.",
      "Nennen Sie mindestens zwei Strategien gegen Prüfungsangst.",
      "Begründen Sie, warum diese Strategien helfen können.",
      "Schreiben Sie ein klares Fazit.",
    ],
    supportStructure: [
      "Einleitung: Ich finde Julias Meinung interessant, weil ...",
      "Meinung: Ich stimme ihr zu / Ich stimme ihr nur teilweise zu.",
      "Begründung 1: Gute Vorbereitung kann helfen, weil ...",
      "Begründung 2: Entspannungsübungen sind wichtig, damit ...",
      "Fazit: Deshalb denke ich, dass ...",
    ],
    vocabulary: [
      "die Prüfungsangst",
      "der Stress",
      "unter Druck stehen",
      "die Leistung beeinflussen",
      "sich vorbereiten",
      "Entspannungsübungen machen",
      "ruhig bleiben",
      "sich sicher fühlen",
      "positive Gedanken",
      "eine Methode finden",
    ],
    template: "Ich finde Julias Meinung sehr richtig. Viele Menschen haben Prüfungsangst, weil sie unter Druck stehen und Angst vor schlechten Noten haben. Meiner Meinung nach kann gute Stressbewältigung helfen. Wenn man früh lernt, Pausen macht und tief atmet, fühlt man sich sicherer. Außerdem sollte man positiv denken. Zusammenfassend denke ich, dass Prüfungsangst normal ist, aber man sie mit der richtigen Methode reduzieren kann.",
  },
  reading: {
    title: "Lesen Sie den Text über Prüfungen im Bildungswesen und beantworten Sie die sieben Fragen.",
    instructions: "Lesen Sie zuerst den Text. Wählen Sie danach bei jeder Frage genau eine Antwort.",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Prüfungen und Bildungssystem",
    text: {
      title: "Die Bedeutung der Prüfungen im Bildungswesen",
      questionTitle: "Fragen",
      paragraphs: [
        "In vielen Ländern sind Prüfungen der zentrale Bestandteil des Bildungssystems. Sie bestimmen, ob Schüler und Studenten in die nächste Klasse kommen, ein Studium beginnen oder eine Ausbildung abschließen können. Doch wie gerecht sind diese Prüfungen wirklich? In den letzten Jahren haben viele Bildungsexperten diskutiert, ob Prüfungen wirklich die beste Methode sind, um Wissen zu messen. Einige Experten meinen, dass Prüfungen oft nur das Kurzzeitgedächtnis testen und nicht die tiefe Auseinandersetzung mit einem Thema fördern. Andere sehen darin ein wichtiges Instrument, um Leistungsstandards zu gewährleisten.",
        "Es gibt unterschiedliche Arten von Prüfungen: schriftliche Prüfungen, mündliche Prüfungen und praktische Prüfungen. Jede Prüfungsform hat ihre eigenen Vorteile und Herausforderungen. Schriftliche Prüfungen sind oft standardisiert und leicht zu bewerten, während mündliche Prüfungen ein tieferes Verständnis des Lernstoffes erfordern. Praktische Prüfungen hingegen testen oft Fähigkeiten, die im Alltag oder Beruf relevant sind.",
        "Ein weiteres Thema ist der Prüfungsstress. Viele Schüler leiden unter Prüfungsangst und erzielen deshalb schlechtere Ergebnisse, als sie es in einer stressfreien Umgebung tun würden. Es gibt viele Methoden, um Prüfungsangst zu bekämpfen, zum Beispiel durch Entspannungstechniken, eine gute Vorbereitung und ausreichend Schlaf vor der Prüfung. Dennoch bleibt das Thema Prüfungsstress ein wichtiges Problem im Bildungssystem.",
        "Bildungsexperten diskutieren, ob alternative Formen der Leistungsbewertung, wie zum Beispiel kontinuierliche Leistungskontrollen, Projekte oder Hausarbeiten, gerechter sind als einmalige Prüfungen. Diese Methoden bieten oft mehr Möglichkeiten, individuelle Stärken zu zeigen und weniger Druck aufzubauen. Allerdings sind sie auch zeitaufwändiger und schwieriger zu standardisieren.",
        "Am Ende bleibt die Frage, wie Prüfungen in Zukunft gestaltet werden sollten, um fair, gerecht und stressfrei zu sein. Klar ist, dass das Bildungssystem in vielen Ländern vor großen Herausforderungen steht und sich weiterentwickeln muss, um den Bedürfnissen der Schüler gerecht zu werden.",
      ],
      questions: [
        { stem: "Welche Meinung vertreten Bildungsexperten zu Prüfungen?", options: ["a) Prüfungen sind die beste Methode, um Wissen zu testen.", "b) Prüfungen fördern das Kurzzeitgedächtnis.", "c) Prüfungen sind völlig nutzlos.", "d) Prüfungen fördern die Kreativität."] },
        { stem: "Welche Arten von Prüfungen werden im Text genannt?", options: ["a) Nur schriftliche Prüfungen.", "b) Nur mündliche Prüfungen.", "c) Schriftliche, mündliche und praktische Prüfungen.", "d) Es werden keine Prüfungen erwähnt."] },
        { stem: "Was wird als eine der Herausforderungen von Prüfungen erwähnt?", options: ["a) Zu wenig Prüfungsarten.", "b) Prüfungsstress.", "c) Prüfungen sind zu einfach.", "d) Prüfungen fördern die Teamarbeit."] },
        { stem: "Was sind alternative Methoden zur Wissensbewertung laut Text?", options: ["a) Mehrere Prüfungen hintereinander.", "b) Projekte und Hausarbeiten.", "c) Nur mündliche Prüfungen.", "d) Keine Prüfungen mehr."] },
        { stem: "Welche Prüfungsform erfordert ein tieferes Verständnis des Lernstoffes?", options: ["a) Schriftliche Prüfungen.", "b) Mündliche Prüfungen.", "c) Praktische Prüfungen.", "d) Es gibt keinen Unterschied."] },
        { stem: "Welche Methoden helfen gegen Prüfungsangst?", options: ["a) Noch mehr Lernen.", "b) Entspannungstechniken und gute Vorbereitung.", "c) Weniger Prüfungen.", "d) Kürzere Prüfungen."] },
        { stem: "Was wird als Vorteil von alternativen Bewertungsmethoden beschrieben?", options: ["a) Sie sind einfacher zu organisieren.", "b) Sie sind fairer und individueller.", "c) Sie machen keinen Unterschied.", "d) Sie sind nur für schriftliche Prüfungen geeignet."] },
      ],
    },
  },
  listening: {
    title: "Hören Sie den Text über Prüfungsangst und beantworten Sie die fünf Fragen.",
    instructions: "Hören Sie aufmerksam zu. Notieren Sie die richtigen Antwortbuchstaben und reichen Sie sie im Submit-Tab ein.",
    image: "https://images.unsplash.com/photo-1516534775068-ba3e7458af70?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Stressbewältigung vor einer Prüfung",
    embedUrl: "https://drive.google.com/file/d/1FrNgfUChKDYLnd0pUO6-LnGppeHSet8E/preview",
    externalUrl: "https://drive.google.com/file/d/1FrNgfUChKDYLnd0pUO6-LnGppeHSet8E/view?usp=sharing",
    videoTitle: "B1 Day 16 Prüfungsangst und Stressbewältigung Hören",
    submitRequired: true,
    selfCheckText: "Hören ist Teil dieser Übung. Reichen Sie Ihre fünf Antwortbuchstaben im Submit-Tab ein.",
    questions: [
      { stem: "Welche Vorbereitungsmethode wird im Hörtext empfohlen?", options: ["a) Intensives Lernen in der Nacht vor der Prüfung.", "b) Regelmäßiges Lernen und Pausen machen.", "c) Die Prüfung ignorieren.", "d) Nur in der Gruppe lernen."] },
      { stem: "Was wird als wichtige Methode zur Stressbewältigung genannt?", options: ["a) Meditation und positives Denken.", "b) Langes Lernen ohne Pausen.", "c) Frühes Aufstehen am Prüfungstag.", "d) Ein sehr großes Frühstück."] },
      { stem: "Welche Rolle spielt das Gespräch mit anderen bei Prüfungsangst?", options: ["a) Es ist nicht wichtig.", "b) Es verschlimmert die Situation.", "c) Es kann helfen, die Angst zu reduzieren.", "d) Man sollte das Gespräch vermeiden."] },
      { stem: "Was ist laut dem Hörtext der Schlüssel zum Erfolg bei Prüfungen?", options: ["a) Viele Entspannungsübungen.", "b) Sich klarzumachen, dass die Prüfung nur eine Momentaufnahme ist.", "c) Gute Beziehungen zu Lehrern.", "d) Sehr viel Schlaf."] },
      { stem: "Was sollte man laut dem Hörtext vermeiden?", options: ["a) Langfristige Vorbereitung.", "b) Gespräche über die Angst.", "c) Negative Gedanken und Stress.", "d) Den Prüfungsstoff durchzugehen."] },
    ],
    steps: [
      "Hören Sie den Text einmal komplett.",
      "Lesen Sie die Fragen und Antwortmöglichkeiten.",
      "Hören Sie wichtige Stellen ein zweites Mal.",
      "Schreiben Sie Ihre fünf Antwortbuchstaben in den Submit-Tab.",
    ],
  },
  submitListening: true,
  submitWritingDescription: "Paste your opinion about Prüfungsangst and Stressbewältigung.",
  submitReadingDescription: "Paste your seven reading answer letters.",
  submitListeningDescription: "Paste your five listening answer letters.",
};

export default function B1Day16PruefungsangstStressbewaeltigungWorkbookPage() {
  return <B1StandardWorkbookPage config={B1_DAY16_PRUEFUNGSANGST_STRESSBEWAELTIGUNG_WORKBOOK_CONFIG} />;
}
