import React from "react";
import B1StandardWorkbookPage from "./B1StandardWorkbookPage";

export const B1_DAY18_WEGE_ZUM_WUNSCHBERUF_WORKBOOK_CONFIG = {
  day: 18,
  chapter: "6.18",
  assignmentKey: "B1-6.18",
  workbookId: "B1Day18WegeZumWunschberuf",
  title: "Wege zum Wunschberuf",
  subtitle: "Sprich über Traumberufe, Ausbildung, Qualifikationen, Bewerbungen und Karrierechancen. Teil 1 ist Gruppenpraxis; Teil 2, Teil 3 und Teil 4 bereitest du für die Abgabe vor.",
  heroImage: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1600&q=80",
  heroAlt: "Menschen sprechen über Karriere und Beruf",
  speaking: {
    question: "Wie kannst du deinen Wunschberuf erreichen?",
    instructions: "Bereite eine kurze B1-Präsentation vor. Erkläre deinen Wunschberuf, die nötige Ausbildung, wichtige Fähigkeiten und mögliche Karrierechancen.",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Bewerbung und Karriereplanung",
    ideaTitle: "Zentrales Thema: Wege zum Wunschberuf",
    ideaIntro: "In this chapter, we'll engage in group exercises discussing paths to a dream job, qualifications, applications and future career opportunities.",
    ideaGroups: [
      {
        title: "1. Traumberuf finden",
        items: [
          "Was interessiert mich? Persönliche Stärken und Leidenschaften entdecken.",
          "Welche Berufe gibt es? Verschiedene Branchen und Berufsfelder erkunden.",
          "Praktika und Berufserfahrung: den Job ausprobieren.",
        ],
      },
      {
        title: "2. Ausbildung und Qualifikation",
        items: [
          "Schule und Schulabschlüsse: Hauptschule, Realschule, Abitur.",
          "Studium an der Universität oder Fachhochschule: theoretische Ausbildung.",
          "Berufsausbildung im dualen System: Lernen und Arbeiten gleichzeitig.",
          "Zertifikate und Weiterbildungen: Spezialisierungen und neue Kenntnisse erwerben.",
        ],
      },
      {
        title: "3. Bewerbungsprozess",
        items: [
          "Lebenslauf schreiben: Ausbildung, Erfahrung und Fähigkeiten zeigen.",
          "Bewerbungsschreiben: erklären, warum man diesen Job möchte.",
          "Vorstellungsgespräch vorbereiten: typische Fragen üben.",
        ],
      },
      {
        title: "4. Wichtige Fähigkeiten und Eigenschaften",
        items: [
          "Kommunikationsfähigkeit: gut sprechen und schreiben können.",
          "Zeitmanagement: Aufgaben organisieren.",
          "Teamfähigkeit: gut mit anderen zusammenarbeiten.",
          "Digitale Kompetenzen: Computer- und Technikkenntnisse.",
        ],
      },
      {
        title: "5. Karrierechancen und Zukunft",
        items: [
          "Aufstiegsmöglichkeiten: Weiterbildung und neue Positionen.",
          "Arbeiten im Ausland: internationale Chancen.",
          "Selbstständigkeit: ein eigenes Unternehmen gründen.",
        ],
      },
      {
        title: "6. Eigene Erfahrungen und Meinung",
        items: [
          "Welcher Beruf interessiert dich? Warum?",
          "Welche Ausbildung oder Qualifikationen brauchst du für diesen Beruf?",
          "Welche Fähigkeiten möchtest du noch verbessern?",
        ],
      },
    ],
    exampleTitle: "Beispielantwort",
    exampleSteps: [
      "Mein Wunschberuf ist Lehrer, weil ich gerne mit Menschen arbeite.",
      "Ich brauche dafür ein Studium an der Universität.",
      "Zurzeit mache ich ein Praktikum an einer Schule, um Erfahrungen zu sammeln.",
      "Ich möchte meine Kommunikationsfähigkeiten verbessern, weil sie im Unterricht wichtig sind.",
    ],
    activityTitle: "Struktur deiner Präsentation",
    activityPoints: [
      "Begrüßung und Vorstellung des Themas.",
      "Inhalt und Struktur: Erkläre, welchen Beruf du erreichen möchtest und worüber du sprichst.",
      "Persönliche Erfahrung: Beschreibe deine Interessen, Stärken oder Erfahrungen.",
      "Situation in deinem Heimatland: Erkläre, welche Wege es dort zu diesem Beruf gibt.",
      "Vor- und Nachteile: Nenne Vorteile und Herausforderungen dieses Berufs oder Ausbildungswegs.",
      "Schluss: Fasse zusammen, wie du deinen Wunschberuf erreichen kannst.",
    ],
    activityOrdered: true,
    answerStructure: [
      "Begrüße dein Publikum und nenne deinen Wunschberuf.",
      "Erkläre, warum dich dieser Beruf interessiert.",
      "Nenne die nötige Ausbildung oder Qualifikation.",
      "Beschreibe wichtige Fähigkeiten und Eigenschaften.",
      "Erkläre Praktika, Bewerbung oder Weiterbildung als Weg zum Ziel.",
      "Gib ein Fazit mit deinem nächsten Schritt.",
    ],
    usefulPhrases: [
      "Mein Wunschberuf ist ...",
      "Ich interessiere mich für diesen Beruf, weil ...",
      "Für diesen Beruf braucht man ...",
      "Es ist wichtig, ... zu ...",
      "Ich möchte meine ... verbessern.",
      "Ein Vorteil dieses Berufs ist, dass ...",
      "Eine Herausforderung ist, dass ...",
      "Zusammenfassend kann ich sagen, dass ...",
    ],
  },
  writing: {
    title: "Gibt es verschiedene Wege zum Wunschberuf?",
    instructions: "Lesen Sie Lenas Meinung und schreiben Sie Ihre eigene Antwort. Erklären Sie, ob es verschiedene Wege zum Wunschberuf gibt und welche Wege Sie sinnvoll finden.",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Berufsplanung und Bewerbung schreiben",
    sourceTitle: "Aufgabe",
    sourceText: "Gibt es verschiedene Wege zum Wunschberuf? Schreiben Sie Ihre Meinung. Lena: Es gibt viele Wege, um den Wunschberuf zu erreichen. Ich stimme dem zu, denn manche Menschen machen eine Ausbildung, andere studieren an einer Universität. Dennoch kann man auch durch Praktika oder Weiterbildungen ein Ziel erreichen. Ich finde, dass jeder seinen eigenen Weg wählen sollte, je nachdem, was am besten zu ihm passt. Was denken Sie darüber?",
    taskPoints: [
      "Beziehen Sie sich kurz auf Lenas Meinung.",
      "Schreiben Sie, ob Sie zustimmen oder nicht.",
      "Nennen Sie verschiedene Wege: Ausbildung, Studium, Praktikum oder Weiterbildung.",
      "Erklären Sie, warum Menschen unterschiedliche Wege brauchen.",
      "Schreiben Sie ein klares Fazit.",
    ],
    supportStructure: [
      "Einleitung: Ich finde Lenas Meinung interessant, weil ...",
      "Meinung: Ich stimme ihr zu / Ich stimme ihr teilweise zu.",
      "Begründung 1: Eine Ausbildung ist sinnvoll, wenn ...",
      "Begründung 2: Ein Studium oder Praktikum kann helfen, weil ...",
      "Fazit: Deshalb denke ich, dass jeder den Weg wählen sollte, der zu ihm passt.",
    ],
    vocabulary: [
      "der Wunschberuf",
      "die Ausbildung",
      "das Studium",
      "das Praktikum",
      "die Weiterbildung",
      "die Qualifikation",
      "Berufserfahrung sammeln",
      "sich bewerben",
      "eigene Stärken erkennen",
      "zum Ziel passen",
    ],
    template: "Ich finde Lenas Meinung sehr richtig. Es gibt nicht nur einen Weg zum Wunschberuf, weil jeder Mensch andere Stärken und Möglichkeiten hat. Manche brauchen ein Studium, andere erreichen ihr Ziel durch eine Ausbildung oder praktische Erfahrung. Praktika sind auch wichtig, weil man den Beruf besser kennenlernen kann. Meiner Meinung nach sollte jeder den Weg wählen, der zu seinen Interessen und Lebensumständen passt. Zusammenfassend denke ich, dass verschiedene Wege zum Wunschberuf möglich und sinnvoll sind.",
  },
  reading: {
    title: "Lesen Sie den Text über Berufswahl und beantworten Sie die sieben Fragen.",
    instructions: "Lesen Sie zuerst den Text. Wählen Sie danach bei jeder Frage genau eine Antwort.",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Berufswahl und Karriereentscheidung",
    text: {
      title: "Berufswahl – Wunsch oder Realität?",
      questionTitle: "Fragen",
      paragraphs: [
        "Die Berufswahl ist eine der wichtigsten Entscheidungen im Leben. Schon in der Schulzeit werden Jugendliche gefragt, was sie später einmal beruflich machen möchten. Doch während einige schon früh eine klare Vorstellung haben, sind andere unsicher oder lassen sich von äußeren Einflüssen, wie Eltern oder Lehrern, leiten. Die Frage ist: Sollte man seinen Traumberuf verfolgen oder lieber einen Beruf wählen, der Sicherheit und ein gutes Einkommen bietet?",
        "Die Wahl des Berufs ist oft nicht nur eine Frage der Leidenschaft, sondern auch eine der Vernunft. Einige Berufe sind sehr beliebt, aber die Chancen, einen Job in diesem Bereich zu finden, sind gering. Andere Berufe bieten mehr Sicherheit, sind aber vielleicht nicht so spannend. Viele junge Menschen stehen daher vor der schwierigen Entscheidung: Soll ich meinen Traum verfolgen oder lieber auf Nummer sicher gehen?",
        "Ein weiteres Problem ist, dass sich der Arbeitsmarkt ständig verändert. Was heute ein gefragter Beruf ist, kann morgen schon nicht mehr relevant sein. Das bedeutet, dass Flexibilität und die Bereitschaft, sich weiterzubilden, in der modernen Arbeitswelt immer wichtiger werden. Dennoch bleibt der Wunsch nach einem Traumberuf oft stark, besonders bei jungen Menschen.",
        "Experten empfehlen, bei der Berufswahl sowohl die eigenen Interessen als auch die realen Bedingungen des Arbeitsmarktes zu berücksichtigen. Eine gute Mischung aus Leidenschaft und Vernunft kann der Schlüssel zu einer erfolgreichen Karriere sein. Letztendlich muss jeder für sich selbst entscheiden, welche Prioritäten bei der Berufswahl am wichtigsten sind.",
      ],
      questions: [
        { stem: "Welche Faktoren beeinflussen die Berufswahl laut Text?", options: ["a) Nur die Leidenschaft.", "b) Nur die Sicherheit.", "c) Leidenschaft und Vernunft.", "d) Nur das Einkommen."] },
        { stem: "Was wird im Text als wichtiger Aspekt der modernen Arbeitswelt genannt?", options: ["a) Sicherheit.", "b) Flexibilität und Weiterbildung.", "c) Beliebte Berufe.", "d) Elternrat."] },
        { stem: "Welche Empfehlung geben Experten laut Text?", options: ["a) Nur den Traumberuf verfolgen.", "b) Einen gut bezahlten Beruf wählen.", "c) Eine Mischung aus Leidenschaft und Vernunft finden.", "d) Auf äußere Einflüsse hören."] },
        { stem: "Warum ist es schwierig, den Traumberuf zu verfolgen?", options: ["a) Die Berufe verändern sich nicht.", "b) Der Traumberuf ist nicht immer gefragt.", "c) Der Traumberuf ist immer unsicher.", "d) Man kann nie wissen, was man will."] },
        { stem: "Was sollten junge Menschen laut Text bei der Berufswahl berücksichtigen?", options: ["a) Nur die Leidenschaft.", "b) Nur das Gehalt.", "c) Die realen Bedingungen auf dem Arbeitsmarkt.", "d) Nur den Rat der Eltern."] },
        { stem: "Was passiert oft mit beliebten Berufen laut Text?", options: ["a) Sie werden zu unsicheren Berufen.", "b) Sie bleiben immer gefragt.", "c) Sie sind nur kurzfristig gefragt.", "d) Sie haben immer schlechte Bedingungen."] },
        { stem: "Wie kann man laut dem Text erfolgreich im Beruf sein?", options: ["a) Durch Flexibilität und Bereitschaft zur Weiterbildung.", "b) Durch die Wahl eines festen Berufs.", "c) Durch die Konzentration auf hohe Gehälter.", "d) Durch völlige Sicherheit in der Berufswahl."] },
      ],
    },
  },
  listening: {
    title: "Hören Sie den Text über Berufswahl und beantworten Sie die fünf Fragen.",
    instructions: "Hören Sie aufmerksam zu. Notieren Sie die richtigen Antwortbuchstaben und reichen Sie sie im Submit-Tab ein.",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Beratung zur Berufswahl",
    embedUrl: "https://www.youtube-nocookie.com/embed/t0OIJ3Upz18",
    externalUrl: "https://youtu.be/t0OIJ3Upz18",
    videoTitle: "B1 Day 18 Wege zum Wunschberuf Hören",
    submitRequired: true,
    selfCheckText: "Hören ist Teil dieser Übung. Reichen Sie Ihre fünf Antwortbuchstaben im Submit-Tab ein.",
    questions: [
      { stem: "Was wird als erstes wichtiges Kriterium bei der Berufswahl genannt?", options: ["a) Hohe Gehälter.", "b) Spaß an der Arbeit.", "c) Eine feste Stelle.", "d) Gute Arbeitszeiten."] },
      { stem: "Warum sollte man Praktika machen?", options: ["a) Um ein gutes Gehalt zu bekommen.", "b) Um den Traumberuf zu garantieren.", "c) Um Einblicke in das Berufsfeld zu erhalten.", "d) Um sicherzustellen, dass man keine Fehler macht."] },
      { stem: "Was sollte man laut dem Hörtext neben dem Traumberuf auch beachten?", options: ["a) Ob es genug Stellen im Beruf gibt.", "b) Ob der Beruf sehr einfach ist.", "c) Ob der Beruf gute Arbeitszeiten hat.", "d) Ob man den Beruf ohne Ausbildung ausüben kann."] },
      { stem: "Welche Balance ist laut dem Hörtext wichtig?", options: ["a) Zwischen Spaß und Freizeit.", "b) Zwischen Wunsch und Realität.", "c) Zwischen Gehalt und Urlaub.", "d) Zwischen Arbeit und Familie."] },
      { stem: "Was wird laut dem Hörtext empfohlen, wenn man sich nicht sicher ist, welchen Beruf man wählen soll?", options: ["a) Sich keine Sorgen machen.", "b) Einen Beruf nach dem Gehalt wählen.", "c) Flexibel sein und sich anpassen.", "d) Immer den Beruf wechseln, wenn man unzufrieden ist."] },
    ],
    steps: [
      "Hören Sie den Text einmal komplett.",
      "Lesen Sie die Fragen und Antwortmöglichkeiten.",
      "Hören Sie wichtige Stellen ein zweites Mal.",
      "Schreiben Sie Ihre fünf Antwortbuchstaben in den Submit-Tab.",
    ],
  },
  submitListening: true,
  submitWritingDescription: "Paste your opinion about Wege zum Wunschberuf.",
  submitReadingDescription: "Paste your seven reading answer letters.",
  submitListeningDescription: "Paste your five listening answer letters.",
};

export default function B1Day18WegeZumWunschberufWorkbookPage() {
  return <B1StandardWorkbookPage config={B1_DAY18_WEGE_ZUM_WUNSCHBERUF_WORKBOOK_CONFIG} />;
}
