import React from "react";
import B1StandardWorkbookPage from "./B1StandardWorkbookPage";

export const B1_DAY12_ABENTEUER_IN_DER_NATUR_WORKBOOK_CONFIG = {
  day: 12,
  chapter: "4.12",
  assignmentKey: "B1-4.12",
  workbookId: "B1Day12AbenteuerInDerNatur",
  title: "Abenteuer in der Natur",
  subtitle: "Bearbeite Teil 1 bis Teil 4. Teil 1 ist Gruppenpraxis; Teil 2, Teil 3 und Teil 4 bereitest du für die Abgabe vor.",
  heroImage: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
  heroAlt: "Menschen erleben ein Abenteuer in einer Berglandschaft",
  speaking: {
    question: "Welches Abenteuer in der Natur hat dich am meisten beeindruckt und welche Erfahrungen hast du dabei gemacht?",
    instructions: "Bereite eine kurze B1-Präsentation über dein beeindruckendstes Natur-Abenteuer vor. Sprich über Ort, Umgebung, Erlebnis, Herausforderungen und was du gelernt hast.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Berge und Natur als Abenteuerort",
    ideaTitle: "Zentrales Thema: Mein beeindruckendstes Natur-Abenteuer",
    ideaIntro: "In this chapter, we'll engage in group exercises discussing nature adventures, personal experiences, challenges and lessons learned.",
    ideaGroups: [
      {
        title: "1. Natur",
        items: [
          "Wo warst du? Ich war in den Bergen / im Wald / am Meer / in der Wüste / auf einer Insel.",
          "Art der Umgebung: Berge, See, Fluss, Wald, Meer, Nationalpark.",
          "Wetter und Jahreszeit: Sommer, Winter, Frühling, Herbst, sonnig, kalt, heiß.",
        ],
      },
      {
        title: "2. Abenteuer",
        items: [
          "Art des Abenteuers: Wandern, Camping, Kajakfahren, Tauchen, Klettern, Safari.",
          "Dauer: ein Tag, ein Wochenende, eine Woche.",
          "Allein oder mit anderen: allein, mit Freunden, mit meiner Familie, mit einer Gruppe.",
        ],
      },
      {
        title: "3. Erlebnisse",
        items: [
          "Was war besonders schön? Die Aussicht war atemberaubend. Ich habe die Ruhe genossen.",
          "Tiere und Pflanzen: Ich habe einen Adler / eine Schlange / einen Wal gesehen.",
          "Essen und Unterkunft: Wir haben draußen gekocht. Wir haben in einem Zelt geschlafen.",
        ],
      },
      {
        title: "4. Herausforderungen",
        items: [
          "Schwierigkeiten: Es hat stark geregnet. Ich habe mich verlaufen. Es war sehr kalt.",
          "Lösung: Ich habe eine Karte benutzt. Ich habe Hilfe gefunden. Ich bin ruhig geblieben.",
          "Lernmoment: Ich bin geduldiger geworden. Ich kann jetzt ein Feuer machen.",
        ],
      },
    ],
    exampleTitle: "Beispielantwort",
    exampleSteps: [
      "Mein beeindruckendstes Natur-Abenteuer war eine Wanderung in den Alpen.",
      "Ich war mit Freunden eine Woche in den Bergen.",
      "Die Aussicht war wunderschön und wir haben wilde Tiere gesehen.",
      "Die größte Herausforderung war das Wetter: Es hat stark geregnet, aber wir haben uns mit warmer Kleidung geschützt.",
      "Ich habe gelernt, wie man ein Zelt aufbaut und wie wichtig gute Vorbereitung ist.",
    ],
    activityTitle: "Struktur der Präsentation",
    activityPoints: [
      "Begrüßung und Vorstellung des Themas.",
      "Inhalt und Struktur der Präsentation: Erklären Sie, worüber Sie sprechen werden.",
      "Persönliche Erfahrung: Berichten Sie von Ihrem eigenen Abenteuer in der Natur.",
      "Situation in Ihrem Heimatland: Beschreiben Sie, wie Naturabenteuer in Ihrem Land erlebt werden.",
      "Vor- und Nachteile: Nennen Sie positive und negative Aspekte und begründen Sie Ihre Meinung.",
      "Schluss und Dank: Fassen Sie Ihre Präsentation zusammen.",
    ],
    activityOrdered: true,
    answerStructure: [
      "Begrüßen Sie Ihr Publikum und nennen Sie das Thema.",
      "Beschreiben Sie Ort, Umgebung, Wetter und Jahreszeit.",
      "Erzählen Sie, was Sie erlebt haben und mit wem Sie unterwegs waren.",
      "Nennen Sie eine Herausforderung und erklären Sie, wie Sie das Problem gelöst haben.",
      "Vergleichen Sie kurz Vor- und Nachteile von Naturabenteuern.",
      "Sagen Sie, was Sie gelernt haben, und schließen Sie mit einem Dank.",
    ],
    usefulPhrases: [
      "Mein beeindruckendstes Natur-Abenteuer war ...",
      "Ich war allein / mit Freunden / mit meiner Familie unterwegs.",
      "Besonders schön war, dass ...",
      "Die größte Herausforderung war, dass ...",
      "Trotzdem habe ich gelernt, dass ...",
      "In meinem Heimatland erlebt man Naturabenteuer oft ...",
    ],
  },
  writing: {
    title: "Schreiben Sie einen informellen Brief an Ihren Freund Felix über ein spannendes Abenteuer.",
    instructions: "Sie haben kürzlich ein spannendes Abenteuer erlebt – zum Beispiel eine Reise, eine Wanderung oder ein besonderes Erlebnis. Schreiben Sie einen informellen Brief und erzählen Sie davon.",
    image: "https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Ein Reisender schreibt nach einem Abenteuer",
    sourceTitle: "Aufgabe",
    sourceText: "Sie haben kürzlich ein spannendes Abenteuer erlebt – zum Beispiel eine aufregende Reise, eine Wanderung oder ein besonderes Erlebnis. Schreiben Sie einen informellen Brief an Ihren Freund Felix und erzählen Sie ihm davon.",
    taskPoints: [
      "Begrüßen Sie Felix und fragen Sie kurz, wie es ihm geht.",
      "Erklären Sie, welches Abenteuer Sie erlebt haben und wo es war.",
      "Beschreiben Sie zwei wichtige Erlebnisse oder Eindrücke.",
      "Nennen Sie eine Schwierigkeit und wie Sie sie gelöst haben.",
      "Schreiben Sie, was Sie gelernt haben oder warum das Erlebnis besonders war.",
      "Beenden Sie den Brief freundlich.",
    ],
    supportStructure: [
      "Anrede: Lieber Felix,",
      "Einleitung: Wie geht es dir? Ich möchte dir von meinem Abenteuer erzählen.",
      "Hauptteil 1: Ort, Zeit, Personen und Aktivität beschreiben.",
      "Hauptteil 2: Erlebnisse, Gefühle und Herausforderung beschreiben.",
      "Schluss: Lernmoment, Einladung zu einer Antwort und Gruß.",
    ],
    vocabulary: [
      "das Abenteuer",
      "die Wanderung",
      "die Aussicht",
      "atemberaubend",
      "sich verlaufen",
      "die Herausforderung",
      "die Vorbereitung",
      "draußen kochen",
      "im Zelt schlafen",
      "unvergesslich",
    ],
    template: "Lieber Felix,\n\nwie geht es dir? Ich hoffe, dir geht es gut. Ich möchte dir heute von meinem letzten Abenteuer erzählen.\n\nLetzte Woche war ich ... Dort habe ich ... Besonders schön war ...\n\nEs gab auch ein Problem: ... Zum Glück habe ich ... Dadurch habe ich gelernt, dass ...\n\nDas Erlebnis war für mich sehr besonders, weil ... Schreib mir bald zurück!\n\nViele Grüße\n...",
  },
  reading: {
    title: "Lesen Sie den Text über Abenteuer und beantworten Sie die sieben Fragen.",
    instructions: "Lesen Sie zuerst den vollständigen Text. Wählen Sie danach bei jeder Frage genau eine Antwort.",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Abenteuer in Wald und Natur",
    text: {
      title: "Was bedeutet Abenteuer?",
      questionTitle: "Fragen",
      paragraphs: [
        "Abenteuer ist ein Begriff, der für jeden Menschen etwas anderes bedeuten kann. Für manche Menschen ist Abenteuer gleichbedeutend mit Reisen in ferne Länder, während andere den Nervenkitzel in Extremsportarten suchen. Doch was macht ein Abenteuer wirklich aus?",
        "Viele Menschen sehnen sich nach Abenteuern, weil sie das Bedürfnis haben, aus ihrem Alltagstrott auszubrechen. Der Reiz des Unbekannten und die Möglichkeit, etwas Neues zu erleben, spielen dabei eine große Rolle. Besonders bei jungen Menschen ist der Wunsch nach Abenteuern weit verbreitet. Eine Weltreise, das Besteigen eines Berges oder das Erkunden von Wäldern – all das sind Abenteuer, die unvergessliche Erlebnisse versprechen.",
        "Jedoch hat jede Form des Abenteuers auch ihre Schattenseiten. Abenteuer können mit Risiken verbunden sein, sei es durch gefährliche Situationen oder finanzielle Schwierigkeiten. Nicht jeder Mensch ist bereit, diese Risiken einzugehen. Doch für diejenigen, die sich darauf einlassen, kann das Abenteuer eine unvergessliche Erfahrung sein, die ihnen neue Perspektiven auf das Leben eröffnet.",
        "Es gibt auch Abenteurer, die ihre Abenteuer im Alltag finden. Ein neues Hobby ausprobieren, sich beruflich neu orientieren oder einfach einmal eine andere Perspektive einnehmen – all das kann ebenso abenteuerlich sein wie eine Reise um die Welt.",
        "Am Ende bleibt die Frage, ob ein Leben ohne Abenteuer wirklich lebenswert ist. Manche Menschen sind glücklich, wenn sie in ihrem geregelten Alltag bleiben können, während andere den Nervenkitzel und die Unvorhersehbarkeit eines Abenteuers benötigen. Die Entscheidung liegt bei jedem selbst.",
      ],
      questions: [
        { stem: "Was bedeutet für viele Menschen das Abenteuer?", options: ["a) Der Nervenkitzel des Unbekannten.", "b) Die Freude am Alltag.", "c) Die Routine des Lebens.", "d) Das Risiko, das es mit sich bringt."] },
        { stem: "Warum suchen besonders junge Menschen nach Abenteuern?", options: ["a) Um eine neue Karriere zu finden.", "b) Um den Alltag zu durchbrechen.", "c) Um Stabilität zu gewinnen.", "d) Um finanzielle Probleme zu lösen."] },
        { stem: "Was kann ein Abenteuer mit sich bringen?", options: ["a) Nur positive Erfahrungen.", "b) Risiken und Herausforderungen.", "c) Sicherheit und Ruhe.", "d) Eine genaue Planung."] },
        { stem: "Wie können Abenteurer im Alltag Abenteuer finden?", options: ["a) Indem sie nur reisen.", "b) Durch alltägliche Veränderungen.", "c) Durch gefährliche Aktivitäten.", "d) Indem sie nichts Neues ausprobieren."] },
        { stem: "Was ist ein Risiko bei Abenteuern?", options: ["a) Beruflicher Erfolg.", "b) Finanzielle Unsicherheiten.", "c) Ein geregeltes Leben.", "d) Eine klare Zukunftsplanung."] },
        { stem: "Was verspricht ein Abenteuer?", options: ["a) Einfache Lösungen.", "b) Unvergessliche Erlebnisse.", "c) Vorhersehbarkeit.", "d) Keine Veränderung."] },
        { stem: "Wie entscheiden sich manche Menschen in Bezug auf Abenteuer?", options: ["a) Sie meiden jede Form von Abenteuer.", "b) Sie suchen den Nervenkitzel im Alltag.", "c) Sie wählen ein Leben voller Routine.", "d) Sie ignorieren das Unbekannte."] },
      ],
    },
  },
  listening: {
    title: "Hören Sie den Bericht über ein Abenteuer in den Bergen und beantworten Sie die fünf Fragen.",
    instructions: "Hören Sie aufmerksam zu. Notieren Sie die richtigen Antwortbuchstaben und reichen Sie sie im Submit-Tab ein.",
    image: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Bergwanderung als Hörthema",
    embedUrl: "https://drive.google.com/file/d/1Kefw-ko0KUViOIPlu81UxKra2RIP6J5H/preview",
    externalUrl: "https://drive.google.com/file/d/1Kefw-ko0KUViOIPlu81UxKra2RIP6J5H/view?usp=sharing",
    videoTitle: "B1 Day 12 Abenteuer in der Natur Hören",
    submitRequired: true,
    selfCheckText: "Hören ist Teil dieser Übung. Reichen Sie Ihre fünf Antwortbuchstaben im Submit-Tab ein.",
    questions: [
      { stem: "Warum entschied sich der Sprecher, allein in die Berge zu gehen?", options: ["a) Er wollte sich einer körperlichen Herausforderung stellen.", "b) Er wollte Zeit mit seinen Freunden verbringen.", "c) Er wollte neue Städte entdecken.", "d) Er musste aus beruflichen Gründen reisen."] },
      { stem: "Was war das Ziel am ersten Tag?", options: ["a) Ein abgelegener Bergsee.", "b) Der höchste Gipfel der Region.", "c) Ein kleines Dorf in den Bergen.", "d) Ein Campingplatz mit vielen Touristen."] },
      { stem: "Welche Tiere sah der Sprecher während seiner Wanderung?", options: ["a) Adler und ein Reh.", "b) Bären und Wölfe.", "c) Eichhörnchen und Hasen.", "d) Kühe und Schafe."] },
      { stem: "Welche Schwierigkeit trat während der Reise auf?", options: ["a) Der Sprecher wurde von einem Tier angegriffen.", "b) Das Wetter änderte sich plötzlich.", "c) Das Essen ging aus.", "d) Der Sprecher verlor seine Ausrüstung."] },
      { stem: "Wie fühlte sich der Sprecher, nachdem er in die Zivilisation zurückkehrte?", options: ["a) Erschöpft und enttäuscht.", "b) Erschöpft und stolz.", "c) Erleichtert und gelangweilt.", "d) Motiviert, sofort eine neue Reise zu beginnen."] },
    ],
    steps: [
      "Hören Sie den Bericht einmal komplett.",
      "Lesen Sie die Fragen und Antwortmöglichkeiten.",
      "Hören Sie schwierige Stellen ein zweites Mal.",
      "Schreiben Sie Ihre fünf Antwortbuchstaben in den Submit-Tab.",
    ],
  },
  submitListening: true,
  submitWritingDescription: "Paste your informal letter to Felix about your adventure.",
  submitReadingDescription: "Paste your seven reading answer letters.",
  submitListeningDescription: "Paste your five listening answer letters.",
};

export default function B1Day12AbenteuerInDerNaturWorkbookPage() {
  return <B1StandardWorkbookPage config={B1_DAY12_ABENTEUER_IN_DER_NATUR_WORKBOOK_CONFIG} />;
}
