import React from "react";
import B1StandardWorkbookPage from "./B1StandardWorkbookPage";

export const B1_DAY17_WIE_LERNT_MAN_AM_BESTEN_WORKBOOK_CONFIG = {
  day: 17,
  chapter: "5.17",
  assignmentKey: "B1-5.17",
  workbookId: "B1Day17WieLerntManAmBesten",
  title: "Wie lernt man am besten?",
  subtitle: "Vergleiche Lernmethoden, Lernumgebung, Zeitmanagement und Motivation. Teil 1 ist Gruppenpraxis; Teil 2, Teil 3 und Teil 4 bereitest du für die Abgabe vor.",
  heroImage: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?auto=format&fit=crop&w=1600&q=80",
  heroAlt: "Effektiv lernen mit Büchern und Laptop",
  speaking: {
    question: "Was hilft dir, effektiv zu lernen?",
    instructions: "Bereite eine kurze B1-Präsentation vor. Erkläre deine besten Lernmethoden, deine Lernumgebung, dein Zeitmanagement und deine persönliche Erfahrung.",
    image: "https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Schüler lernt effektiv",
    ideaTitle: "Zentrales Thema: Wie lernt man am besten?",
    ideaIntro: "In this chapter, we'll engage in group exercises discussing learning methods, learning environment, time management, motivation and personal learning strategies.",
    ideaGroups: [
      {
        title: "1. Lernmethoden",
        items: [
          "Notizen machen: wichtigste Informationen aufschreiben.",
          "Hörbücher oder Podcasts: zuhören und wiederholen.",
          "Texte lesen und markieren: wichtige Stellen hervorheben.",
          "Mit anderen sprechen oder in Gruppen lernen: Austausch mit Freunden oder Lehrern.",
          "Lernen mit Apps und Spielen: digitale Methoden nutzen.",
        ],
      },
      {
        title: "2. Lernumgebung",
        items: [
          "Ruhiger Arbeitsplatz: wenig Ablenkung.",
          "Gute Beleuchtung und bequemer Stuhl: Konzentration verbessern.",
          "Handy ausschalten: keine Ablenkung durch soziale Medien.",
          "Leise Musik oder Stille: hilft beim Fokussieren.",
        ],
      },
      {
        title: "3. Zeitmanagement",
        items: [
          "Feste Lernzeiten planen: jeden Tag zur gleichen Zeit lernen.",
          "Pausen machen: zum Beispiel Pomodoro-Technik mit 25 Minuten Lernen und 5 Minuten Pause.",
          "Lernziele setzen: Was möchte ich heute erreichen?",
          "Wiederholung einplanen: Gelerntes regelmäßig wiederholen.",
        ],
      },
      {
        title: "4. Motivation und Konzentration",
        items: [
          "Realistische Ziele setzen und kleine Erfolge feiern.",
          "Belohnungen geben: nach dem Lernen eine Pause oder ein kleines Geschenk.",
          "Entspannungsübungen machen: Meditation oder kurze Spaziergänge helfen.",
          "Visuelle Hilfsmittel nutzen: Mindmaps, Diagramme oder Karten.",
        ],
      },
      {
        title: "5. Eigene Erfahrungen und Meinung",
        items: [
          "Welche Lernmethoden funktionieren für dich am besten?",
          "Lernst du lieber allein oder in einer Gruppe? Warum?",
          "Was sind deine größten Herausforderungen beim Lernen?",
        ],
      },
    ],
    exampleTitle: "Beispielantwort",
    exampleSteps: [
      "Ich lerne am besten, wenn ich mir Notizen mache und in einer ruhigen Umgebung bin.",
      "Ich benutze oft die Pomodoro-Technik, um konzentriert zu bleiben.",
      "Außerdem finde ich es hilfreich, mit Freunden über das Thema zu sprechen.",
    ],
    activityTitle: "Struktur deiner Präsentation",
    activityPoints: [
      "Begrüßung und Vorstellung des Themas.",
      "Inhalt und Struktur: Erkläre, worüber du sprechen wirst.",
      "Persönliche Erfahrung: Beschreibe, wie du selbst am besten lernst.",
      "Situation in deinem Heimatland: Erkläre, wie Schüler dort meistens lernen.",
      "Vor- und Nachteile: Nenne Vorteile und Nachteile verschiedener Lernmethoden.",
      "Schluss und Dank: Fasse deine Meinung zusammen und bedanke dich.",
    ],
    activityOrdered: true,
    answerStructure: [
      "Begrüße dein Publikum und nenne das Thema.",
      "Beschreibe zwei oder drei Lernmethoden.",
      "Erkläre, welche Lernumgebung dir hilft.",
      "Sprich über Zeitmanagement, Pausen und Wiederholung.",
      "Nenne Vorteile und Nachteile von Alleinlernen oder Gruppenlernen.",
      "Gib deine persönliche Meinung und schließe mit einem Dank.",
    ],
    usefulPhrases: [
      "Ich lerne am besten, wenn ...",
      "Für mich ist wichtig, dass ...",
      "Eine gute Methode ist, ... zu ...",
      "Ich finde es hilfreich, ...",
      "Ein Vorteil dieser Methode ist, dass ...",
      "Ein Nachteil ist, dass ...",
      "Zusammenfassend kann ich sagen, dass ...",
    ],
  },
  writing: {
    title: "Wie lernt man am besten?",
    instructions: "Lesen Sie Tims Meinung und schreiben Sie Ihre eigene Antwort. Sagen Sie, welche Lernmethoden Sie gut finden und warum.",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Meinung zum effektiven Lernen schreiben",
    sourceTitle: "Aufgabe",
    sourceText: "Wie lernt man am besten? Schreiben Sie Ihre Meinung. Tim: Jeder Mensch lernt anders. Ich denke, dass es wichtig ist, eine gute Methode zu finden. Manche lernen gut mit Büchern, andere mit Videos oder in Gruppen. Dennoch ist regelmäßiges Üben immer wichtig. Ich finde, dass man sich Ziele setzen und Pausen machen sollte, um effektiv zu lernen. Was denken Sie darüber?",
    taskPoints: [
      "Beziehen Sie sich kurz auf Tims Meinung.",
      "Schreiben Sie, ob Sie zustimmen oder nicht.",
      "Nennen Sie zwei Lernmethoden, die für Sie gut funktionieren.",
      "Erklären Sie, warum Ziele, Pausen oder Wiederholung wichtig sind.",
      "Schreiben Sie ein klares Fazit.",
    ],
    supportStructure: [
      "Einleitung: Ich finde Tims Meinung interessant, weil ...",
      "Meinung: Ich stimme ihm zu / Ich stimme ihm teilweise zu.",
      "Begründung 1: Eine gute Methode ist ..., weil ...",
      "Begründung 2: Pausen und Wiederholung helfen, damit ...",
      "Fazit: Deshalb denke ich, dass ...",
    ],
    vocabulary: [
      "die Lernmethode",
      "Notizen machen",
      "regelmäßig üben",
      "Ziele setzen",
      "Pausen machen",
      "Wiederholung einplanen",
      "sich konzentrieren",
      "in einer Gruppe lernen",
      "effektiv lernen",
      "den Lernstoff behalten",
    ],
    template: "Ich finde Tims Meinung sehr richtig. Jeder Mensch lernt anders, deshalb sollte man eine passende Methode finden. Ich lerne am besten, wenn ich mir Notizen mache und den Lernstoff regelmäßig wiederhole. Außerdem helfen mir Pausen, weil ich mich danach besser konzentrieren kann. Meiner Meinung nach sind klare Ziele und eine ruhige Umgebung sehr wichtig. Zusammenfassend denke ich, dass man am besten lernt, wenn man regelmäßig übt und die Methode zu einem passt.",
  },
  reading: {
    title: "Lesen Sie den Text über effektives Lernen und beantworten Sie die sieben Fragen.",
    instructions: "Lesen Sie zuerst den Text. Wählen Sie danach bei jeder Frage genau eine Antwort.",
    image: "https://images.unsplash.com/photo-1456406644174-8ddd4cd52a06?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Effektives Lernen mit Notizen",
    text: {
      title: "Effektiver lernen – Tipps und Tricks",
      questionTitle: "Fragen",
      paragraphs: [
        "In der heutigen Welt ist es wichtiger denn je, effizient und effektiv zu lernen. Viele Menschen haben Schwierigkeiten, den Überblick über den Lernstoff zu behalten oder wissen nicht, wie sie ihr Gedächtnis optimal nutzen können. Es gibt jedoch viele Techniken, die helfen können, den Lernprozess zu verbessern.",
        "Eine wichtige Methode ist das sogenannte aktive Lernen. Dabei geht es darum, den Lernstoff nicht nur zu lesen oder zu hören, sondern aktiv damit zu arbeiten. Das kann durch das Schreiben von Zusammenfassungen, das Erstellen von Mindmaps oder das Erklären des Stoffes an andere geschehen. Forscher haben herausgefunden, dass der Lernstoff dadurch besser im Gedächtnis bleibt.",
        "Ein weiterer wichtiger Punkt ist die Planung. Es ist hilfreich, einen Lernplan zu erstellen und feste Lernzeiten festzulegen. Dabei sollte man darauf achten, regelmäßige Pausen einzuplanen. Das Gehirn braucht Zeit, um die Informationen zu verarbeiten, und Pausen helfen dabei, die Konzentration zu behalten.",
        "Auch der Schlaf spielt eine große Rolle beim Lernen. In Studien wurde gezeigt, dass das Gehirn im Schlaf das Gelernte verarbeitet und speichert. Wer also auf ausreichend Schlaf verzichtet, riskiert, dass das Wissen nicht vollständig abgespeichert wird.",
        "Eine beliebte Methode zum besseren Lernen ist auch das Wiederholen. Dabei wird der Lernstoff in regelmäßigen Abständen wiederholt, um ihn im Langzeitgedächtnis zu verankern. Diese Methode, die auch spaced repetition genannt wird, wird besonders beim Sprachenlernen oft eingesetzt.",
        "Am Ende ist es wichtig, die richtige Lernmethode für sich selbst zu finden. Jeder Mensch lernt anders, und was für den einen gut funktioniert, kann für den anderen nicht hilfreich sein.",
      ],
      questions: [
        { stem: "Was ist aktives Lernen laut dem Text?", options: ["a) Nur Lesen und Hören des Lernstoffes.", "b) Aktives Arbeiten mit dem Lernstoff, z.B. durch Zusammenfassungen.", "c) Der Stoff wird einmal durchgearbeitet.", "d) Nur Gruppenarbeit."] },
        { stem: "Welche Rolle spielt der Schlaf beim Lernen?", options: ["a) Schlaf spielt keine Rolle.", "b) Schlaf hilft, den Stoff zu vergessen.", "c) Schlaf hilft, das Gelernte zu speichern.", "d) Schlaf ist nur für die körperliche Erholung wichtig."] },
        { stem: "Was hilft dem Gehirn, die Informationen besser zu verarbeiten?", options: ["a) Intensives, langes Lernen ohne Pausen.", "b) Regelmäßige Pausen.", "c) Kurze Lerneinheiten von 5 Minuten.", "d) Nur nachts lernen."] },
        { stem: "Was ist spaced repetition?", options: ["a) Das einmalige Wiederholen des Lernstoffs.", "b) Das regelmäßige Wiederholen des Lernstoffs.", "c) Das Vermeiden von Wiederholungen.", "d) Eine spezielle Technik für Sportler."] },
        { stem: "Wie kann man laut dem Text den Lernstoff länger behalten?", options: ["a) Durch aktives Lernen und Wiederholung.", "b) Durch das Lernen in Gruppen.", "c) Nur durch Mindmaps.", "d) Durch Nichtstun."] },
        { stem: "Welche Methode wird besonders beim Sprachenlernen angewendet?", options: ["a) Mindmaps erstellen.", "b) Gruppenarbeit.", "c) Spaced repetition.", "d) Schlaf."] },
        { stem: "Was ist ein Vorteil von Lernplänen?", options: ["a) Sie helfen, Zeit zu sparen.", "b) Sie bringen Struktur in den Lernprozess.", "c) Sie verhindern Prüfungsstress.", "d) Sie sind für alle Schüler gleich."] },
      ],
    },
  },
  listening: {
    title: "Hören Sie den Text über Lerntechniken und beantworten Sie die fünf Fragen.",
    instructions: "Hören Sie aufmerksam zu. Notieren Sie die richtigen Antwortbuchstaben und reichen Sie sie im Submit-Tab ein.",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Digitale Lerntechniken und Konzentration",
    embedUrl: "https://www.youtube-nocookie.com/embed/NCfwHzAHoJI?rel=0&playsinline=1",
    externalUrl: "https://youtu.be/NCfwHzAHoJI",
    videoTitle: "B1 Day 17 Wie lernt man am besten Hören",
    submitRequired: true,
    selfCheckText: "Hören ist Teil dieser Übung. Reichen Sie Ihre fünf Antwortbuchstaben im Submit-Tab ein.",
    questions: [
      { stem: "Was versteht man unter chunking?", options: ["a) Der Lernstoff wird in kleinere Abschnitte aufgeteilt.", "b) Man lernt den Stoff in einem Stück.", "c) Man ignoriert schwierige Themen.", "d) Man lernt alles am Prüfungstag."] },
      { stem: "Warum ist regelmäßiges Wiederholen wichtig?", options: ["a) Es spart Zeit.", "b) Es hilft, den Stoff dauerhaft zu behalten.", "c) Es hilft nur beim Sprachenlernen.", "d) Es verbessert die Prüfungsnoten."] },
      { stem: "Was ist laut dem Hörtext ein wichtiger Faktor beim Lernen?", options: ["a) Die Länge der Lernzeit.", "b) Eine ruhige und aufgeräumte Umgebung.", "c) Das Lernen mit Freunden.", "d) Ein fester Platz in der Bibliothek."] },
      { stem: "Wie kann man den Lernprozess reflektieren?", options: ["a) Indem man schwierige Themen ignoriert.", "b) Indem man sich selbst Fragen zum Gelernten stellt.", "c) Indem man nur stur auswendig lernt.", "d) Indem man den Stoff vor sich hin liest."] },
      { stem: "Was sollte man tun, nachdem man ein Lernziel erreicht hat?", options: ["a) Sofort weiterlernen.", "b) Sich selbst belohnen.", "c) Neue Ziele setzen.", "d) Eine lange Pause machen."] },
    ],
    steps: [
      "Hören Sie den Text einmal komplett.",
      "Lesen Sie die Fragen und Antwortmöglichkeiten.",
      "Hören Sie wichtige Stellen ein zweites Mal.",
      "Schreiben Sie Ihre fünf Antwortbuchstaben in den Submit-Tab.",
    ],
  },
  submitListening: true,
  submitWritingDescription: "Paste your opinion about how to learn best.",
  submitReadingDescription: "Paste your seven reading answer letters.",
  submitListeningDescription: "Paste your five listening answer letters.",
};

export default function B1Day17WieLerntManAmBestenWorkbookPage() {
  return <B1StandardWorkbookPage config={B1_DAY17_WIE_LERNT_MAN_AM_BESTEN_WORKBOOK_CONFIG} />;
}
