import React, { useMemo, useState } from "react";
import { styles } from "../styles";

const D = {
1:["Persönliche Identität",[["sich identifizieren mit + Dat","to identify with","Viele Menschen identifizieren sich mit mehreren Kulturen."],["geprägt sein von + Dat","to be shaped by","Unsere Identität ist oft von Familie und Erfahrungen geprägt."],["Wert legen auf + Akk","to attach importance to","Ich lege großen Wert auf persönliche Freiheit."],["sich unterscheiden von + Dat","to differ from","Meine Erfahrungen unterscheiden sich von denen meiner Freunde."]]],
2:["Alltag und Zeitmanagement",[["sich konzentrieren auf + Akk","to focus on","Ich konzentriere mich morgens auf anspruchsvolle Aufgaben."],["abhängen von + Dat","to depend on","Gutes Zeitmanagement hängt von klaren Prioritäten ab."],["verzichten auf + Akk","to do without","Während der Arbeit verzichte ich auf unnötige Benachrichtigungen."],["sich beschäftigen mit + Dat","to deal with","Am Nachmittag beschäftige ich mich mit organisatorischen Aufgaben."]]],
3:["Arbeit und Beruf",[["sich bewerben um + Akk","to apply for","Sie bewirbt sich um eine verantwortungsvolle Stelle."],["verfügen über + Akk","to possess","Bewerber sollten über relevante Berufserfahrung verfügen."],["sich spezialisieren auf + Akk","to specialize in","Er hat sich auf digitales Marketing spezialisiert."],["profitieren von + Dat","to benefit from","Beschäftigte profitieren von regelmäßiger Weiterbildung."]]],
4:["Bildung und Lernen",[["teilnehmen an + Dat","to participate in","Viele Studierende nehmen an zusätzlichen Kursen teil."],["sich vorbereiten auf + Akk","to prepare for","Sie bereitet sich gezielt auf die Prüfung vor."],["profitieren von + Dat","to benefit from","Lernende profitieren von konstruktivem Feedback."],["sich auseinandersetzen mit + Dat","to engage with","Im Studium setzt man sich mit komplexen Themen auseinander."]]],
5:["Gesundheit und Wohlbefinden",[["leiden unter + Dat","to suffer from","Viele Beschäftigte leiden unter dauerhaftem Stress."],["sich erholen von + Dat","to recover from","Nach einer Belastung muss sich der Körper erholen."],["achten auf + Akk","to pay attention to","Man sollte auf ausreichend Schlaf achten."],["sich auswirken auf + Akk","to affect","Bewegungsmangel wirkt sich negativ auf die Gesundheit aus."]]],
6:["Migration und Integration",[["sich integrieren in + Akk","to integrate into","Zugewanderte möchten sich in die Gesellschaft integrieren."],["teilhaben an + Dat","to participate in","Sprachkenntnisse erleichtern die Teilhabe am gesellschaftlichen Leben."],["sich anpassen an + Akk","to adapt to","Neue Einwohner müssen sich teilweise an andere Regeln anpassen."],["beitragen zu + Dat","to contribute to","Begegnungen tragen zu gegenseitigem Verständnis bei."]]],
7:["Gesellschaftliche Vielfalt",[["umgehen mit + Dat","to deal with","Eine offene Gesellschaft muss respektvoll mit Vielfalt umgehen."],["sich einsetzen für + Akk","to advocate for","Viele Organisationen setzen sich für Gleichberechtigung ein."],["profitieren von + Dat","to benefit from","Unternehmen können von unterschiedlichen Perspektiven profitieren."],["führen zu + Dat","to lead to","Vorurteile können zu gesellschaftlichen Konflikten führen."]]],
8:["Reisen und Mobilität",[["sich entscheiden für + Akk","to choose","Viele Reisende entscheiden sich für die Bahn."],["abhängen von + Dat","to depend on","Die Wahl des Verkehrsmittels hängt von der Strecke ab."],["verzichten auf + Akk","to do without","Auf kurzen Strecken kann man auf das Auto verzichten."],["beitragen zu + Dat","to contribute to","Öffentliche Verkehrsmittel tragen zum Klimaschutz bei."]]],
9:["Wohnen und Nachbarschaft",[["sich beschweren über + Akk","to complain about","Die Mieter beschweren sich über den Lärm."],["sich einigen auf + Akk","to agree on","Die Nachbarn einigen sich auf feste Ruhezeiten."],["sich erkundigen nach + Dat","to ask about","Sie erkundigt sich nach den Nebenkosten."],["Rücksicht nehmen auf + Akk","to show consideration for","In einem Wohnhaus sollte man Rücksicht auf andere nehmen."]]],
10:["Konsum und Geld",[["achten auf + Akk","to pay attention to","Beim Einkauf achte ich auf Preis und Qualität."],["sich entscheiden für + Akk","to choose","Viele Verbraucher entscheiden sich für günstigere Alternativen."],["verzichten auf + Akk","to do without","Manche Menschen verzichten bewusst auf unnötige Käufe."],["sich auswirken auf + Akk","to affect","Werbung kann sich stark auf Kaufentscheidungen auswirken."]]],
11:["Gesellschaft und Integration",[["teilhaben an + Dat","to participate in","Alle Menschen sollten am gesellschaftlichen Leben teilhaben können."],["Zugang haben zu + Dat","to have access to","Bildung schafft Zugang zu neuen Chancen."],["sich einsetzen für + Akk","to advocate for","Vereine setzen sich für Integration ein."],["beitragen zu + Dat","to contribute to","Gemeinsame Projekte tragen zum Zusammenhalt bei."]]],
12:["Kultur und Freizeit",[["teilnehmen an + Dat","to participate in","Viele Jugendliche nehmen an kulturellen Veranstaltungen teil."],["sich interessieren für + Akk","to be interested in","Ich interessiere mich für moderne Kunst."],["sich begeistern für + Akk","to be enthusiastic about","Viele Menschen begeistern sich für Live-Musik."],["sich beschäftigen mit + Dat","to engage with","In meiner Freizeit beschäftige ich mich mit Fotografie."]]],
13:["Familie und Generationen",[["Verantwortung übernehmen für + Akk","to take responsibility for","Eltern übernehmen Verantwortung für ihre Kinder."],["abhängen von + Dat","to depend on","Familienmodelle hängen von sozialen Bedingungen ab."],["sich kümmern um + Akk","to take care of","Viele Erwachsene kümmern sich um ältere Angehörige."],["führen zu + Dat","to lead to","Unterschiedliche Erwartungen können zu Konflikten führen."]]],
14:["Freundschaft und soziale Beziehungen",[["sich verlassen auf + Akk","to rely on","In einer guten Freundschaft kann man sich aufeinander verlassen."],["achten auf + Akk","to pay attention to","Freunde sollten auf persönliche Grenzen achten."],["sprechen mit + Dat über + Akk","to talk with someone about","Man sollte offen mit Freunden über Probleme sprechen."],["sich einigen auf + Akk","to agree on","Bei Konflikten kann man sich auf eine Lösung einigen."]]],
15:["Ernährung und Konsumverhalten",[["achten auf + Akk","to pay attention to","Viele Menschen achten auf eine ausgewogene Ernährung."],["verzichten auf + Akk","to do without","Manche verzichten auf stark verarbeitete Lebensmittel."],["sich entscheiden für + Akk","to choose","Immer mehr Verbraucher entscheiden sich für regionale Produkte."],["sich auswirken auf + Akk","to affect","Ernährungsgewohnheiten wirken sich auf die Gesundheit aus."]]],
16:["Digitalisierung im Alltag",[["zugreifen auf + Akk","to access","Nutzer können jederzeit auf digitale Dienste zugreifen."],["abhängen von + Dat","to depend on","Viele Arbeitsprozesse hängen von stabilen Systemen ab."],["schützen vor + Dat","to protect from","Starke Passwörter schützen vor Datenmissbrauch."],["umgehen mit + Dat","to deal with","Alle sollten verantwortungsvoll mit persönlichen Daten umgehen."]]],
17:["Mobilität und Stadtleben",[["investieren in + Akk","to invest in","Städte investieren in den öffentlichen Nahverkehr."],["beitragen zu + Dat","to contribute to","Grünflächen tragen zu einer höheren Lebensqualität bei."],["leiden unter + Dat","to suffer from","Viele Großstädte leiden unter Verkehrsproblemen."],["sich auswirken auf + Akk","to affect","Stadtplanung wirkt sich direkt auf den Alltag der Bewohner aus."]]],
18:["Natur, Klima und Verantwortung",[["beitragen zu + Dat","to contribute to","Jeder kann zum Klimaschutz beitragen."],["verzichten auf + Akk","to do without","Viele Menschen verzichten häufiger auf das Auto."],["warnen vor + Dat","to warn of","Forschende warnen vor den Folgen des Klimawandels."],["führen zu + Dat","to lead to","Extremwetter kann zu großen Schäden führen."]]],
19:["Freiwilligenarbeit und Engagement",[["sich engagieren für + Akk","to volunteer for","Viele Bürger engagieren sich für soziale Projekte."],["sich einsetzen für + Akk","to advocate for","Ehrenamtliche setzen sich für benachteiligte Menschen ein."],["mitwirken an + Dat","to participate in","Freiwillige wirken an lokalen Projekten mit."],["beitragen zu + Dat","to contribute to","Ehrenamt trägt zum gesellschaftlichen Zusammenhalt bei."]]],
20:["Technologie und Arbeit der Zukunft",[["sich auswirken auf + Akk","to affect","Automatisierung wirkt sich auf viele Berufe aus."],["sich vorbereiten auf + Akk","to prepare for","Beschäftigte müssen sich auf neue Anforderungen vorbereiten."],["investieren in + Akk","to invest in","Unternehmen investieren in digitale Weiterbildung."],["verfügen über + Akk","to possess","Fachkräfte müssen über neue Kompetenzen verfügen."]]],
21:["Migration und neue Lebenswege",[["sich entscheiden für + Akk","to decide on","Manche Menschen entscheiden sich für einen Neuanfang im Ausland."],["sich anpassen an + Akk","to adapt to","Nach einem Umzug muss man sich an neue Strukturen anpassen."],["teilhaben an + Dat","to participate in","Sprache hilft dabei, am Alltag teilzuhaben."],["zurückführen auf + Akk","to attribute to","Migration lässt sich oft auf mehrere Gründe zurückführen."]]],
22:["Demokratie und Mitbestimmung",[["sich beteiligen an + Dat","to participate in","Bürger sollten sich an politischen Entscheidungen beteiligen."],["sich einsetzen für + Akk","to advocate for","Viele Initiativen setzen sich für mehr Transparenz ein."],["Stellung nehmen zu + Dat","to take a position on","Politiker müssen zu gesellschaftlichen Fragen Stellung nehmen."],["abhängen von + Dat","to depend on","Vertrauen in Institutionen hängt von transparenter Kommunikation ab."]]],
23:["Work-Life-Balance",[["achten auf + Akk","to pay attention to","Beschäftigte sollten auf klare Grenzen achten."],["sich erholen von + Dat","to recover from","Nach intensiver Arbeit muss man sich ausreichend erholen."],["leiden unter + Dat","to suffer from","Viele Menschen leiden unter permanenter Erreichbarkeit."],["sich auswirken auf + Akk","to affect","Dauerstress wirkt sich negativ auf die Leistungsfähigkeit aus."]]],
24:["Wissenschaft und Forschung im Alltag",[["forschen an + Dat","to research","Wissenschaftler forschen an neuen Behandlungsmethoden."],["sich befassen mit + Dat","to deal with","Die Studie befasst sich mit digitaler Gesundheit."],["basieren auf + Dat","to be based on","Wissenschaftliche Aussagen sollten auf überprüfbaren Daten basieren."],["beitragen zu + Dat","to contribute to","Forschung kann zur Lösung gesellschaftlicher Probleme beitragen."]]],
25:["Nachhaltiger Konsum",[["achten auf + Akk","to pay attention to","Beim Einkauf achten viele auf nachhaltige Herstellung."],["verzichten auf + Akk","to do without","Verbraucher können auf unnötige Verpackungen verzichten."],["sich entscheiden für + Akk","to choose","Viele entscheiden sich für langlebige Produkte."],["beitragen zu + Dat","to contribute to","Bewusster Konsum trägt zum Ressourcenschutz bei."]]],
26:["Behörden, Termine und formelle Kommunikation",[["sich wenden an + Akk","to contact","Bei Fragen können Sie sich an die zuständige Behörde wenden."],["bitten um + Akk","to ask for","Ich bitte um einen neuen Termin."],["sich erkundigen nach + Dat","to inquire about","Ich möchte mich nach dem Bearbeitungsstand erkundigen."],["sich beziehen auf + Akk","to refer to","Ich beziehe mich auf Ihr Schreiben vom 10. August."]]],
27:["Prüfungstraining: Argumentieren und Reagieren",[["Stellung nehmen zu + Dat","to take a position on","In der Prüfung soll man zu einem Thema Stellung nehmen."],["sich beziehen auf + Akk","to refer to","Ich beziehe mich auf das Argument meines Gesprächspartners."],["sprechen für/gegen + Akk","to argue for/against","Mehrere Gründe sprechen für diese Lösung."],["eingehen auf + Akk","to address","In einer Diskussion sollte man auf Gegenargumente eingehen."]]],
28:["Review und persönlicher Fortschritt",[["sich konzentrieren auf + Akk","to focus on","Beim Wiederholen konzentriere ich mich auf meine Schwächen."],["sich erinnern an + Akk","to remember","Ich erinnere mich an wichtige Strukturen aus dem Kurs."],["zurückgreifen auf + Akk","to draw on","In der Prüfung kann ich auf gelernte Redemittel zurückgreifen."],["profitieren von + Dat","to benefit from","Ich profitiere von regelmäßiger Selbstkorrektur."]]],
};

const prep = (label) => {
  const m = label.match(/\b(an|auf|aus|bei|für|gegen|in|mit|nach|über|um|unter|von|vor|zu)\b(?=\s*\+|\s+[A-Z])/);
  return m ? m[1] : "";
};

export default function B2TopicCollocationPractice({ day }) {
  const lesson = D[Number(day)];
  const [answers, setAnswers] = useState({});
  const [draft, setDraft] = useState("");
  const questions = useMemo(() => lesson ? lesson[1].slice(0,3).map((item,i)=>({i,label:item[0],answer:prep(item[0])})) : [], [lesson]);
  if (!lesson) return null;
  return <section data-b2-topic-collocations style={{ ...styles.card, display:"grid", gap:14, border:"1px solid #c7d2fe", borderRadius:18 }}>
    <div><span style={{ ...styles.badge, background:"#e0e7ff", color:"#3730a3" }}>B2 · Day {day}</span><h2 style={{ margin:"8px 0 0", fontSize:"1.2rem" }}>Kollokationen · Verben mit Präpositionen</h2><p style={{ margin:"6px 0 0", color:"#475569" }}>{lesson[0]} · Lerne Verb, Präposition und Kasus zusammen.</p></div>
    <div style={{ display:"grid", gap:10 }}>{lesson[1].map(([label,en,example])=><div key={label} style={{ border:"1px solid #e2e8f0", borderRadius:14, padding:12, display:"grid", gap:5 }}><strong>{label}</strong><span style={{ color:"#475569" }}>{en}</span><span>{example}</span></div>)}</div>
    <div style={{ display:"grid", gap:10 }}><strong>Klick-Check · Welche Präposition fehlt?</strong>{questions.map(({i,label,answer})=>{const selected=answers[i];const options=[answer,"mit","von","für"].filter((v,p,a)=>v&&a.indexOf(v)===p).slice(0,3);return <div key={label} style={{ display:"grid", gap:7 }}><span>{label.replace(` ${answer} +`,` ___ +`)}</span><div style={{ display:"flex", gap:7, flexWrap:"wrap" }}>{options.map(o=><button key={o} type="button" onClick={()=>setAnswers(old=>({...old,[i]:o}))} style={{ ...styles.secondaryButton, borderColor:selected===o?(o===answer?"#16a34a":"#dc2626"):"#cbd5e1" }}>{o}</button>)}</div>{selected?<small style={{ color:selected===answer?"#166534":"#9a3412", fontWeight:700 }}>{selected===answer?"Richtig.":`Noch nicht. Richtig: ${answer}`}</small>:null}</div>})}</div>
    <div style={{ border:"1px solid #bfdbfe", borderRadius:14, padding:12, background:"#eff6ff", display:"grid", gap:8 }}><strong>Jetzt produzieren</strong><span>Schreibe zwei eigene B2-Sätze zum Thema und benutze zwei Kombinationen von oben.</span><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={4} placeholder="1. ...\n2. ..." style={{ width:"100%", border:"1px solid #cbd5e1", borderRadius:10, padding:10, font:"inherit" }} /></div>
  </section>;
}
