import React, { useState } from "react";

const tabs = ["sprechen", "schreiben", "lesen", "hören"];
const styles = { page: { maxWidth: 980, margin: "0 auto", padding: "32px 16px 48px", display: "grid", gap: 16 }, title: { fontSize: "clamp(1.6rem, 2.4vw, 2.1rem)", lineHeight: 1.2, color: "#0f172a" }, tabRow: { display: "flex", gap: 8, flexWrap: "wrap" }, tabButton: (active) => ({ border: active ? "1px solid #2563eb" : "1px solid #cbd5e1", background: active ? "#eff6ff" : "#fff", color: "#0f172a", borderRadius: 999, padding: "8px 14px", fontWeight: 700, cursor: "pointer" }) };
const card = { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 16, padding: 20, display: "grid", gap: 10 };
const listSpacing = { margin: 0, paddingLeft: 20, display: "grid", gap: 8, lineHeight: 1.65 };

const C1Day14InnovationUndZukunftWorkbookPage = () => {
  const [activeTab, setActiveTab] = useState("sprechen");
  return (
    <main style={styles.page}>
      <section style={card}><h1 style={{ ...styles.title, margin: 0 }}>C1 · Day 14 Workbook · Innovation und Zukunft</h1><p style={{ margin: 0 }}>Trainiere argumentatives Sprechen/Schreiben mit Fokus auf Prognosen, Abwägung und präzisem Register.</p></section>
      <nav style={styles.tabRow} aria-label="Workbook tabs">{tabs.map((tab) => <button key={tab} type="button" onClick={() => setActiveTab(tab)} style={styles.tabButton(activeTab === tab)}>{tab[0].toUpperCase() + tab.slice(1)}</button>)}</nav>
      {activeTab === "sprechen" && <section style={card}><h2 style={{ margin: 0 }}>Sprechen</h2><p style={{ margin: 0 }}><strong>Aufgabe:</strong> Halte einen 3-4-minütigen Kurzvortrag: „Welche Innovationen werden unseren Alltag in den nächsten zehn Jahren am stärksten prägen?“</p><ul style={listSpacing}><li>Nenne 2-3 konkrete Innovationsfelder.</li><li>Bewerte Chancen und Risiken mit Beispielen.</li><li>Formuliere mindestens zwei Prognosen mit Futur I/Futur II.</li></ul><p style={{ margin: 0 }}><strong>Selbstbewertung:</strong> Habe ich differenziert argumentiert? Waren meine Prognosen sprachlich präzise? War mein Register durchgehend C1-angemessen?</p></section>}
      {activeTab === "schreiben" && <section style={card}><h2 style={{ margin: 0 }}>Schreiben</h2><p style={{ margin: 0 }}><strong>Genre-Auswahl: Meinungsessay / Erörterung.</strong> {/* Rationale: „Innovation und Zukunft“ ist ein gesellschaftlich-digitales Diskussionsthema ohne institutionellen Anfragekontext; daher C1-Erörterung statt formeller Brief. */}</p><p style={{ margin: 0 }}><strong>Situation/Kontext:</strong> Du verfasst für ein überregionales Online-Magazin einen Beitrag zur Leitfrage: „Soll der Staat Zukunftstechnologien stärker fördern – auch wenn Risiken noch nicht vollständig abschätzbar sind?“ (220–280 Wörter)</p><p style={{ margin: 0 }}><strong>Pflichtpunkte:</strong></p><ul style={listSpacing}><li>zwei Gründe für staatliche Förderung</li><li>mindestens ein relevantes Gegenargument mit Risikoaspekt</li><li>eine eigene Prognose für die nächsten zehn Jahre</li><li>eine begründete Schlussposition mit konkreter Empfehlung</li></ul><p style={{ margin: 0 }}><strong>Register/Ton:</strong> formell, sachlich, abwägend, evidenzorientiert.</p><p style={{ margin: 0 }}><strong>Struktur:</strong> Einleitung (Thema + Relevanz) · Hauptteil (Argumente + Gegenargument + Prognose) · Schluss (Position + Ausblick).</p><p style={{ margin: 0 }}><strong>Self-Check:</strong></p><ul style={listSpacing}><li>Kohärenz: Ist der rote Faden klar erkennbar?</li><li>Register: Bleibt der Stil durchgehend formell?</li><li>Grammatik: Setze ich Futurformen/Modalität korrekt ein?</li><li>Wortschatz: Nutze ich präzise C1-Ausdrücke zu Innovation/Politik?</li><li>Aufgabenbezug: Habe ich alle Pflichtpunkte vollständig abgedeckt?</li></ul></section>}
      {activeTab === "lesen" && <section style={card}><h2 style={{ margin: 0 }}>Lesen</h2><p style={{ margin: 0 }}>Lies einen Kommentar zu KI-Regulierung und markiere Kernthese, Prognosen, Einschränkungen und Wertungen.</p><ul style={listSpacing}><li>Welche Aussagen sind belegte Fakten, welche Prognosen?</li><li>Wo nutzt der Text vorsichtige vs. absolute Formulierungen?</li><li>Welche Argumentationsstrategie überzeugt am meisten – und warum?</li></ul><p style={{ margin: 0 }}><strong>Selbstbewertung:</strong> Kann ich Textfunktion und Argumentstruktur klar zusammenfassen?</p></section>}
      {activeTab === "hören" && <section style={card}><h2 style={{ margin: 0 }}>Hören</h2><p style={{ margin: 0 }}>Höre ein Interview mit einer Zukunftsforscherin. Notiere drei Prognosen und wie sicher sie jeweils präsentiert werden.</p><ul style={listSpacing}><li>Welche sprachlichen Marker signalisieren Unsicherheit/Wahrscheinlichkeit?</li><li>Welche Prognose wird am stärksten begründet?</li><li>Welche offene Frage bleibt nach dem Beitrag bestehen?</li></ul><p style={{ margin: 0 }}><strong>Selbstbewertung:</strong> Erkenne ich Nuancen zwischen Wahrscheinlichkeit, Vermutung und Spekulation zuverlässig?</p></section>}
    </main>
  );
};

export default C1Day14InnovationUndZukunftWorkbookPage;
