import React, { useState } from "react";

const HERO_IMAGE = "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1600&q=80";
const tabs = ["sprechen", "schreiben", "lesen", "hören"];
const styles = { page: { maxWidth: 980, margin: "0 auto", padding: "32px 16px 48px", display: "grid", gap: 16 }, title: { fontSize: "clamp(1.6rem, 2.4vw, 2.1rem)", lineHeight: 1.2, color: "#0f172a" }, tabRow: { display: "flex", gap: 8, flexWrap: "wrap" }, tabButton: (active) => ({ border: active ? "1px solid #2563eb" : "1px solid #cbd5e1", background: active ? "#eff6ff" : "#fff", color: "#0f172a", borderRadius: 999, padding: "8px 14px", fontWeight: 700, cursor: "pointer" }) };
const card = { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 16, padding: 20, display: "grid", gap: 10 };
const listSpacing = { margin: 0, paddingLeft: 20, display: "grid", gap: 8, lineHeight: 1.65 };

const C1Day15BildungUndLebenslangesLernenWorkbookPage = () => {
  const [activeTab, setActiveTab] = useState("sprechen");
  return (
    <main style={styles.page}>
      <section style={card}><h1 style={{ ...styles.title, margin: 0 }}>C1 · Day 15 Workbook · Bildung und lebenslanges Lernen</h1><p style={{ margin: 0 }}>Vertiefe argumentatives Sprachhandeln zu Bildungsgerechtigkeit, Weiterbildung und gesellschaftlichem Wandel.</p></section>
      <img src={HERO_IMAGE} alt="Studierende in einer Bibliothek" loading="lazy" style={{ width: "100%", borderRadius: 12, maxHeight: 260, objectFit: "cover", border: "1px solid #e5e7eb" }} />
      <nav style={styles.tabRow} aria-label="Workbook tabs">{tabs.map((tab) => <button key={tab} type="button" onClick={() => setActiveTab(tab)} style={styles.tabButton(activeTab === tab)}>{tab[0].toUpperCase() + tab.slice(1)}</button>)}</nav>
      {activeTab === "sprechen" && <section style={card}><h2 style={{ margin: 0 }}>Sprechen</h2><p style={{ margin: 0 }}><strong>Aufgabe:</strong> Präsentiere in 3-4 Minuten die Frage: „Welche Kompetenzen sind in einer Gesellschaft des lebenslangen Lernens unverzichtbar?“</p><ul style={listSpacing}><li>Nenne mindestens drei Schlüsselkompetenzen.</li><li>Begründe ihre Relevanz für Beruf und gesellschaftliche Teilhabe.</li><li>Stelle einen Zielkonflikt dar (z. B. Chancengleichheit vs. Leistungsdruck).</li></ul><p style={{ margin: 0 }}><strong>Selbstbewertung:</strong> Ist meine Argumentation logisch aufgebaut? Nutze ich präzisen C1-Wortschatz? Spreche ich differenziert und nicht pauschal?</p></section>}
      {activeTab === "schreiben" && <section style={card}><h2 style={{ margin: 0 }}>Schreiben</h2><p style={{ margin: 0 }}><strong>Genre-Auswahl: Meinungsessay / Erörterung.</strong> {/* Rationale: Das Thema „Bildung und lebenslanges Lernen“ ist ein gesellschafts- und bildungspolitisches Diskussionsthema ohne institutionellen Beschwerde-/Antragsrahmen; daher C1-Erörterung. */}</p><p style={{ margin: 0 }}><strong>Situation/Kontext:</strong> Du schreibst für die Rubrik „Gesellschaft im Wandel“ einer Zeitung einen Beitrag zur Frage: „Sollte berufliche Weiterbildung in Deutschland stärker staatlich finanziert werden?“ (220-280 Wörter)</p><p style={{ margin: 0 }}><strong>Pflichtpunkte:</strong></p><ul style={listSpacing}><li>mindestens zwei Argumente für eine stärkere Finanzierung</li><li>mindestens ein differenziertes Gegenargument (z. B. Eigenverantwortung, Kosten, Effizienz)</li><li>ein konkretes Praxisbeispiel aus Arbeitswelt oder Bildungssystem</li><li>deine begründete Position mit umsetzbarem Vorschlag</li></ul><p style={{ margin: 0 }}><strong>Register/Ton:</strong> formell, sachlich, differenzierend, evidenzorientiert.</p><p style={{ margin: 0 }}><strong>Struktur:</strong> Einleitung (Thema + Aktualität) · Hauptteil (Pro-/Contra-Abwägung + Beispiel) · Schluss (Position + Handlungsempfehlung).</p><p style={{ margin: 0 }}><strong>Self-Check:</strong></p><ul style={listSpacing}><li>Kohärenz: Sind Übergänge und Argumentkette klar?</li><li>Register: Bleibt der Stil konsequent formell?</li><li>Grammatik: Nutze ich Nominalisierungen und Passivstrukturen korrekt?</li><li>Wortschatz: Verwende ich präzise Begriffe zu Bildung/Arbeitsmarkt?</li><li>Aufgabenbezug: Habe ich alle Pflichtpunkte vollständig bearbeitet?</li></ul></section>}
      {activeTab === "lesen" && <section style={card}><h2 style={{ margin: 0 }}>Lesen</h2><p style={{ margin: 0 }}>Lies einen Kommentar über Bildungsgerechtigkeit und markiere These, Begründungen, Belege und Schlussfolgerung.</p><ul style={listSpacing}><li>Welche Argumente sind normativ, welche empirisch gestützt?</li><li>Wie wird mit Gegenargumenten umgegangen?</li><li>Welche sprachlichen Mittel erhöhen die Überzeugungskraft?</li></ul><p style={{ margin: 0 }}><strong>Selbstbewertung:</strong> Kann ich Argumentstruktur und Intention präzise zusammenfassen?</p></section>}
      {activeTab === "hören" && <section style={card}><h2 style={{ margin: 0 }}>Hören</h2><p style={{ margin: 0 }}>Höre eine Podiumsdiskussion zur Weiterbildungspflicht in Unternehmen und notiere zentrale Positionen.</p><ul style={listSpacing}><li>Welche Interessen vertreten die Sprecher:innen?</li><li>Welche Kompromissvorschläge werden genannt?</li><li>Welches Argument erscheint am besten begründet – und warum?</li></ul><p style={{ margin: 0 }}><strong>Selbstbewertung:</strong> Erkenne ich Nuancen in Haltung, Gewichtung und Argumentqualität zuverlässig?</p></section>}
    </main>
  );
};

export default C1Day15BildungUndLebenslangesLernenWorkbookPage;
