import React, { useState } from "react";

const HERO_IMAGE = "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1600&q=80";
const tabs = ["sprechen", "schreiben", "lesen", "hören"];
const styles = { page: { maxWidth: 980, margin: "0 auto", padding: "32px 16px 48px", display: "grid", gap: 16 }, title: { fontSize: "clamp(1.6rem, 2.4vw, 2.1rem)", lineHeight: 1.2, color: "#0f172a" }, tabRow: { display: "flex", gap: 8, flexWrap: "wrap" }, tabButton: (active) => ({ border: active ? "1px solid #2563eb" : "1px solid #cbd5e1", background: active ? "#eff6ff" : "#fff", color: "#0f172a", borderRadius: 999, padding: "8px 14px", fontWeight: 700, cursor: "pointer" }) };
const card = { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 16, padding: 20, display: "grid", gap: 10 };
const listSpacing = { margin: 0, paddingLeft: 20, display: "grid", gap: 8, lineHeight: 1.65 };

const C1Day16TechnologieImAlltagWorkbookPage = () => {
  const [activeTab, setActiveTab] = useState("sprechen");
  return (
    <main style={styles.page}>
      <section style={card}><h1 style={{ ...styles.title, margin: 0 }}>C1 · Day 16 Workbook · Technologie im Alltag</h1><p style={{ margin: 0 }}>Trainiere differenzierte Argumentation zu Digitalisierung, Alltagspraxis und gesellschaftlichen Folgen.</p></section>
      <img src={HERO_IMAGE} alt="Digitale Werkzeuge am Arbeitsplatz" loading="lazy" style={{ width: "100%", borderRadius: 12, maxHeight: 260, objectFit: "cover", border: "1px solid #e5e7eb" }} />
      <nav style={styles.tabRow} aria-label="Workbook tabs">{tabs.map((tab) => <button key={tab} type="button" onClick={() => setActiveTab(tab)} style={styles.tabButton(activeTab === tab)}>{tab[0].toUpperCase() + tab.slice(1)}</button>)}</nav>
      {activeTab === "sprechen" && <section style={card}><h2 style={{ margin: 0 }}>Sprechen</h2><p style={{ margin: 0 }}><strong>Aufgabe:</strong> Halte einen 3-4-minütigen Beitrag: „Wie verändert Technologie unseren Alltag – eher positiv oder eher problematisch?“</p><ul style={listSpacing}><li>Nenne mindestens zwei konkrete Alltagsbereiche (z. B. Arbeit, Bildung, Gesundheit, soziale Kontakte).</li><li>Zeige pro Bereich mindestens eine Ursache und eine Folge.</li><li>Formuliere eine ausgewogene persönliche Position mit Beispiel.</li></ul><p style={{ margin: 0 }}><strong>Selbstbewertung:</strong> Sind meine Aussagen logisch verknüpft? Nutze ich präzise C1-Konnektoren (z. B. aufgrund, infolge, sodass)?</p></section>}
      {activeTab === "schreiben" && <section style={card}><h2 style={{ margin: 0 }}>Schreiben</h2><p style={{ margin: 0 }}><strong>Genre-Auswahl: Meinungsessay / Erörterung.</strong> {/* Rationale: „Technologie im Alltag“ ist ein gesellschaftliches Digitalisierungsthema ohne konkreten institutionellen Beschwerde- oder Antragsrahmen; deshalb passt eine C1-Erörterung. */}</p><p style={{ margin: 0 }}><strong>Situation/Kontext:</strong> Du verfasst für ein Online-Magazin den Beitrag: „Sollte der Einsatz von KI-basierten Assistenzsystemen im Alltag stärker reguliert werden?“ (220-280 Wörter)</p><p style={{ margin: 0 }}><strong>Pflichtpunkte:</strong></p><ul style={listSpacing}><li>zwei Argumente für stärkere Regulierung (z. B. Datenschutz, Transparenz)</li><li>mindestens ein Gegenargument (z. B. Innovation, Effizienz, Barrierefreiheit)</li><li>ein konkretes Beispiel aus Schule, Arbeit oder privatem Alltag</li><li>deine klare Schlussposition mit realistischem Vorschlag</li></ul><p style={{ margin: 0 }}><strong>Register/Ton:</strong> formell, sachlich, differenzierend.</p><p style={{ margin: 0 }}><strong>Struktur:</strong> Einleitung (Problemrahmen) · Hauptteil (Abwägung Pro/Contra + Beispiel) · Schluss (Position + Empfehlung).</p><p style={{ margin: 0 }}><strong>Self-Check:</strong></p><ul style={listSpacing}><li>Kohärenz: Ist der Argumentationsgang klar und gut verknüpft?</li><li>Register: Halte ich den formellen Stil konsequent ein?</li><li>Grammatik: Nutze ich Ursache-Wirkung-Strukturen korrekt und variantenreich?</li><li>Wortschatz: Verwende ich präzise Begriffe zu Digitalisierung/Regulierung?</li><li>Aufgabenbezug: Habe ich alle Pflichtpunkte vollständig bearbeitet?</li></ul></section>}
      {activeTab === "lesen" && <section style={card}><h2 style={{ margin: 0 }}>Lesen</h2><p style={{ margin: 0 }}>Lies einen Kommentar über digitale Assistenzsysteme und analysiere die Argumentstruktur.</p><ul style={listSpacing}><li>Welche Ursachen für den Technikeinsatz werden genannt?</li><li>Welche kurzfristigen und langfristigen Folgen werden unterschieden?</li><li>Wie werden Gegenargumente sprachlich relativiert oder integriert?</li></ul><p style={{ margin: 0 }}><strong>Selbstbewertung:</strong> Kann ich Hauptthese, Begründungen und Schlussfolgerung präzise rekonstruieren?</p></section>}
      {activeTab === "hören" && <section style={card}><h2 style={{ margin: 0 }}>Hören</h2><p style={{ margin: 0 }}>Höre ein Streitgespräch zum Thema „Smart Devices im Alltag“ und notiere zentrale Positionen.</p><ul style={listSpacing}><li>Welche Ursache-Wirkung-Ketten nennen die Sprecher:innen?</li><li>Wo unterscheiden sich Bewertung und Prioritäten?</li><li>Welche Kompromisslösung wird vorgeschlagen?</li></ul><p style={{ margin: 0 }}><strong>Selbstbewertung:</strong> Erkenne ich differenzierte Standpunkte und kann ich sie strukturiert wiedergeben?</p></section>}
    </main>
  );
};

export default C1Day16TechnologieImAlltagWorkbookPage;
