import React,{useEffect,useMemo,useState}from"react";
import AppBackButton from"./navigation/AppBackButton";
import{styles}from"../styles";
import{getC2Day1To7Mastery}from"../data/c2Day1To7Mastery";
import{getC2Day8To14Mastery}from"../data/c2Day8To14Mastery";
import{getC2Days6To11GuidedWorkbookConfig}from"../data/c2Days6To11GuidedWorkbook";
const TABS=["learn","speak","write","finish","references"],LABELS={learn:"1. Learn",speak:"2. Speak",write:"3. Write",finish:"4. Finish",references:"5. Ref"};
const card={...styles.card,display:"grid",gap:14,border:"1px solid #e2e8f0",borderRadius:18,boxShadow:"0 10px 26px rgba(15,23,42,.06)"};
const Section=({title,children})=><section style={card}><h2 style={{margin:0,fontSize:"1.18rem"}}>{title}</h2>{children}</section>;
const Step=({n,title,text})=><div style={{border:"1px solid #dbeafe",borderRadius:14,padding:13,background:"#f8fbff",display:"grid",gap:6}}><strong style={{color:"#1e3a8a"}}>{n}. {title}</strong><span style={{color:"#334155",lineHeight:1.65}}>{text}</span></div>;
const Progress=({label,done,detail})=><div style={{border:`1px solid ${done?"#86efac":"#cbd5e1"}`,borderRadius:14,padding:13,background:done?"#f0fdf4":"#fff",display:"grid",gap:4}}><strong>{done?"Complete":"Not complete"} · {label}</strong><span style={{color:"#64748b",fontSize:13}}>{detail}</span></div>;
export default function C2Days6To11GuidedWorkbookPage({lesson}){
 const day=Number(lesson?.day||0),mastery=lesson?.c2Mastery||(day<=7?getC2Day1To7Mastery(day):getC2Day8To14Mastery(day)),config=getC2Days6To11GuidedWorkbookConfig(day),storageKey=`falowen:c2:day${day}:guided-workbook`;
 const[active,setActive]=useState("learn"),[speakPlan,setSpeakPlan]=useState(""),[writingPlan,setWritingPlan]=useState(""),[writingDraft,setWritingDraft]=useState("");
 const[progress,setProgress]=useState(()=>{try{return{learnDone:false,speakDone:false,writeDone:false,confidence:"",reflection:"",...JSON.parse(window.localStorage.getItem(storageKey)||"{}")}}catch{return{learnDone:false,speakDone:false,writeDone:false,confidence:"",reflection:""}}});
 useEffect(()=>{if(typeof window!=="undefined")window.localStorage.setItem(storageKey,JSON.stringify(progress))},[progress,storageKey]);
 const wordCount=useMemo(()=>writingDraft.trim()?writingDraft.trim().split(/\s+/).length:0,[writingDraft]);if(!mastery||!config)return null;const finishReady=progress.learnDone&&progress.speakDone&&progress.writeDone&&Boolean(progress.confidence);
 return <main style={{...styles.container,display:"grid",gap:18}} data-c2-guided-workbook-day={day}><AppBackButton label="Back to Course Book" fallbackPath="/campus/course"/>
 <header style={{...card,padding:"clamp(20px,4vw,34px)",background:"linear-gradient(135deg,#0f172a,#1e3a8a 58%,#2563eb)",color:"#fff"}}><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><span style={{...styles.badge,background:"rgba(255,255,255,.14)",color:"#fff"}}>C2</span><span style={{...styles.badge,background:"rgba(255,255,255,.14)",color:"#fff"}}>Day {day}</span><span style={{...styles.badge,background:"rgba(37,99,235,.9)",color:"#fff"}}>Chapter {mastery.chapter}</span></div><div><h1 style={{margin:0,fontSize:"clamp(2rem,5vw,3.2rem)"}}>{mastery.title}</h1><p style={{margin:"10px 0 0",color:"#dbeafe",lineHeight:1.65}}>{mastery.topic}</p></div><div style={{border:"1px solid rgba(255,255,255,.2)",borderRadius:14,padding:13,background:"rgba(255,255,255,.08)"}}><strong>Today’s C2 control:</strong> {mastery.grammarFocus}</div></header>
 <nav style={{position:"sticky",top:0,zIndex:5,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(108px,1fr))",gap:8,padding:10,border:"1px solid #e2e8f0",borderRadius:18,background:"rgba(248,250,252,.96)"}}>{TABS.map(tab=><button key={tab} type="button" onClick={()=>setActive(tab)} style={{...(active===tab?styles.primaryButton:styles.secondaryButton),borderRadius:999,minHeight:44}}>{LABELS[tab]}</button>)}</nav>
 {active==="learn"?<><Section title={`Think first · ${config.thinkTitle}`}><p style={{margin:0,color:"#475569",lineHeight:1.7}}>{config.thinkIntro}</p><div style={{display:"grid",gap:10}}>{config.learnSteps.map(([title,text],i)=><Step key={title} n={i+1} title={title} text={text}/>)}</div></Section><Section title="Precise vocabulary and collocations"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:10}}>{mastery.vocabulary.map(([word,meaning])=><div key={word} style={{border:"1px solid #e2e8f0",borderRadius:12,padding:12}}><strong>{word}</strong><div style={{color:"#64748b"}}>{meaning}</div></div>)}</div>{mastery.collocations.map(([phrase,meaning,example])=><div key={phrase} style={{border:"1px solid #dbeafe",borderRadius:12,padding:12,background:"#eff6ff"}}><strong>{phrase}</strong> — {meaning}<p style={{margin:"6px 0 0"}}>{example}</p></div>)}</Section><Section title="Grammar & style contrast">{mastery.contrast.map((sentence,i)=><p key={sentence} style={{margin:0}}><strong>Version {i+1}:</strong> {sentence}</p>)}<p style={{margin:0,color:"#475569"}}>Choose the version because of meaning, function, evidence or register—not because it looks more difficult.</p></Section><Section title="Meaning & nuance check"><strong>{mastery.nuance.q}</strong><ol style={{margin:0,paddingLeft:22,lineHeight:1.8}}>{mastery.nuance.o.map(o=><li key={o}>{o}</li>)}</ol><details><summary>Show answer and reasoning</summary><p><strong>{mastery.nuance.o[mastery.nuance.a]}</strong></p><p>{mastery.nuance.e}</p></details><label style={{display:"flex",gap:8,alignItems:"center",fontWeight:700}}><input type="checkbox" checked={progress.learnDone} onChange={e=>setProgress(p=>({...p,learnDone:e.target.checked}))}/>I can explain the grammar/style choice in terms of meaning and function.</label></Section></>:null}
 {active==="speak"?<Section title="Speak · Build the thought before the sentence"><div style={{border:"1px solid #bfdbfe",borderRadius:14,padding:13,background:"#eff6ff",lineHeight:1.7}}><strong>Question:</strong> {config.speakQuestion}</div><div style={{display:"grid",gap:10}}>{config.speakPlan.map((x,i)=><Step key={x} n={i+1} title={x} text="Decide this part before you search for advanced German."/>)}</div><textarea value={speakPlan} onChange={e=>setSpeakPlan(e.target.value)} placeholder="Plan your answer here before speaking..." style={{minHeight:180,border:"1px solid #cbd5e1",borderRadius:12,padding:12,font:"inherit",lineHeight:1.7}}/><label style={{display:"flex",gap:8,alignItems:"center",fontWeight:700}}><input type="checkbox" checked={progress.speakDone} onChange={e=>setProgress(p=>({...p,speakDone:e.target.checked}))}/>I gave a 2–3 minute answer and controlled the target C2 feature deliberately.</label></Section>:null}
 {active==="write"?<Section title="Write · From idea to controlled C2 production"><div style={{border:"1px solid #bfdbfe",borderRadius:14,padding:13,background:"#eff6ff",lineHeight:1.7}}><strong>Task:</strong> {config.writeTask}</div><div style={{display:"grid",gap:10}}>{config.writingSteps.map((x,i)=><Step key={x} n={i+1} title={x} text="Make this decision first, then formulate the German sentence."/>)}</div><label style={{display:"grid",gap:7}}><strong>Planning box</strong><textarea value={writingPlan} onChange={e=>setWritingPlan(e.target.value)} placeholder="Position / criteria / evidence / contrast / conclusion" style={{minHeight:150,border:"1px solid #cbd5e1",borderRadius:12,padding:12,font:"inherit",lineHeight:1.7}}/></label><label style={{display:"grid",gap:7}}><strong>Final German text</strong><textarea value={writingDraft} onChange={e=>setWritingDraft(e.target.value)} placeholder="Write your C2 text here..." style={{minHeight:320,border:"1px solid #cbd5e1",borderRadius:12,padding:12,font:"inherit",lineHeight:1.7}}/></label><div style={{display:"flex",gap:10,flexWrap:"wrap",color:"#475569"}}><span>{wordCount} words</span><span>Target: about {config.targetWords} words</span></div><label style={{display:"flex",gap:8,alignItems:"center",fontWeight:700}}><input type="checkbox" checked={progress.writeDone} onChange={e=>setProgress(p=>({...p,writeDone:e.target.checked}))}/>I revised the text for precision, register, nuance and naturalness.</label></Section>:null}
 {active==="finish"?<Section title={`Finish C2 Day ${day}`}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10}}><Progress label="Learn" done={progress.learnDone} detail="Target C2 decision understood"/><Progress label="Speak" done={progress.speakDone} detail="Spoken production completed"/><Progress label="Write" done={progress.writeDone} detail={`${wordCount} words · revision completed`}/></div><label style={{display:"grid",gap:7}}><strong>Confidence</strong><select value={progress.confidence} onChange={e=>setProgress(p=>({...p,confidence:e.target.value}))} style={styles.select}><option value="">Select confidence</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label style={{display:"grid",gap:7}}><strong>Reflection</strong><textarea value={progress.reflection} onChange={e=>setProgress(p=>({...p,reflection:e.target.value}))} placeholder="What decision became easier today?" style={{minHeight:120,border:"1px solid #cbd5e1",borderRadius:12,padding:12,font:"inherit"}}/></label><div style={{border:`1px solid ${finishReady?"#86efac":"#fde68a"}`,background:finishReady?"#f0fdf4":"#fffbeb",borderRadius:14,padding:12,color:finishReady?"#166534":"#92400e"}}>{finishReady?"Day complete: all learning stages are finished.":"Complete Learn, Speak, Write and choose a confidence level."}</div></Section>:null}
 {active==="references"?<><Section title="Reformulation reference"><p><strong>Starting version:</strong> {mastery.reformulation[0]}</p><details><summary>Show one C2 model</summary><p>{mastery.reformulation[1]}</p></details></Section><Section title="C2 challenge"><p>{mastery.challenge}</p><strong>Final check: meaning · precision · register · evidence/function · natural collocation.</strong></Section></>:null}
 </main>;
}
